akka/akka-projection

.gitignore
.scalafmt.conf
LICENSE
build.sbt
project/CopyrightHeader.scala
project/Dependencies.scala
project/build.properties
project/plugins.sbt
version.sbt

Contains some minimal project setup. 
Most of it is copied from akka-grpc project. The only different is the code formatting. I picked scalafmt (like in Alpakka) and copied .scalafmt from Alpakka project.

project files

---

akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/ProjectionTestKit.scala
akka-projection-testkit/src/test/scala/akka/projection/testkit/ProjectionTestKitSpec.scala

This one builds on top of #47. 
It adds the possibility to use the testkit with a TestSink and control the flow of elements passing through the projection.

ProjectionTestKit with support for TestSink

---

.travis.yml
akka-projection-cassandra/src/main/resources/reference.conf
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/CassandraOffsetStore.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStoreImpl.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala
akka-projection-cassandra/src/test/resources/logback-test.xml
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
build.sbt
docker-compose.yml
docker-files/cassandra.yaml
project/Dependencies.scala

* CassandraProjection
* only added atLeastOnce to start with, will add atMostOnce and grouped in separate PR
* CassandraOffsetStore
* offset stored as string and manifest, similar to Slick OffsetStore
* tests very similar to Slick tests, credit to @renatocaval
Ready for review, but marked as Draft because it's on top of https://github.com/akka/akka-projection/pull/35
If you start reviewing before that PR is merged you can ignore everything in akka-projection-core and akka-projection-slick. I didn't change any of that here.
References #21

Cassandra Projection, #21

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
akka-projection-testkit/src/test/scala/akka/projection/testkit/ProjectionTestKitSpec.scala

* offset not stored in same transaction as user handler
* usage would be to benefit from batching of offsets
* which is probably a very small advantage for jdbc
* it can be more interesting when we add support for user handler
that is not storing in db but the offset should be stored in db, created issue https://github.com/akka/akka-projection/issues/68 for that
References #24

add atLeastOnce in SlickProjection, #24

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala
akka-projection-slick/src/test/scala/akka/projection/slick/OffsetStoreSpec.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestClock.scala

* to be used by back office to see stuck projections
(draft because on top of other PR for the moment, but otherwise ready for review)

add last_updated timestamp in offset table

---

.travis.yml
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/ContainerSessionProvider.scala
project/Dependencies.scala

Use `testcontainers-scala` to spin up a Cassandra container automatically for Cassandra tests.
References #55

Use testcontainers for Cassandra impl

---

akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

* from 45s to 11s
* One part is the tests that are waiting for stream failure, but they
will always wait 3 sec for the assert function to timeout. Better
to use SinkProbe since we only care about the stream failure.
* The second part was the too long interval in PatienceConfig. Decent
value already defined by ScalaTestWithActorTestKit.
References #64

Speedup CassandraProjectionSpec, #64

---

.scalafmt.conf
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

* formated first with scalafmt v2.1.0
* reformatted with v2.4.2 and newlines.afterCurlyLambda = preserve

Preserve new lines after curly lambda

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/Handler.scala
akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java
akka-projection-core/src/main/scala/akka/projection/internal/SourceProviderAdapter.scala
akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala
project/Dependencies.scala

Couldn't write any tests because we need javadsl of the testkit first, but I have prepared for the junit testing. https://github.com/akka/akka-projection/issues/83
References #21

javadsl for CassandraProjection

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-core/src/main/scala/akka/projection/HandlerRecovery.scala
akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala
akka-projection-core/src/main/scala/akka/projection/javadsl/Handler.scala
akka-projection-core/src/main/scala/akka/projection/scaladsl/Handler.scala
akka-projection-core/src/test/resources/logback-test.xml
akka-projection-core/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickSpec.scala
project/Common.scala
project/Dependencies.scala

* moved recovery strategies and implementation to core
* used in CassandraProjection (and SlickProjection)
* new unit test of the HandlerRecoveryImpl
* also found and fixed a few bugs
* problem with at-least-once after 1 in Slick
* problem with at-most-once in Cassandra, async boundary may cause more than one
offset to be saved before processing
References #17
Draft because on top of other PR, but ready for review.

Recovery strategies when handler fails to process, #17

---

.gitignore
build.sbt
docs/src/main/paradox/eventsourced.md
examples/src/test/java/jdocs/eventsourced/CborSerializable.scala
examples/src/test/java/jdocs/eventsourced/EventSourcedDocExample.java
examples/src/test/java/jdocs/eventsourced/ShoppingCart.java
examples/src/test/scala/docs/eventsourced/CborSerializable.scala
examples/src/test/scala/docs/eventsourced/EventSourcedDocExample.scala
examples/src/test/scala/docs/eventsourced/ShoppingCart.scala
project/Dependencies.scala

* examples project in build
* example and basic docs for EventSourcedProvider
* Took the ShoppingCart from the cqrs sample, can be good a somewhat realistic
example that we can use in several places in the documentation
References #79

example and basic docs for EventSourcedProvider, #79

---

akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala
akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java
akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala
project/Dependencies.scala

This supersedes #99 as we realised that the we don't need (for now) a new API around the daemon.

ProjectionBehavior (scala and java API)

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala
akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala
akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java
akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala
akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java
akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala

@patriknw / @seglo, I have been experimenting with some alternatives for the Projection trait while working on #110. 
This is something that I got working and would like to get feedback to decide if I should continue or not. 
Note, I only refactored the code in core, testkit and slick. 
It has a few advantages:
* backoff is applied by common trait, implementors don't need to deal with it
* once started, a projection can't be started again. To start again, we produce a new instance. Basically, `Projection` becomes a factory for `RunningProjection` (more on that later)
* no AtomicBoolean to track if already started or not
The disadvantage is that it makes it a little tedious to implement a Projection, but it makes it safer. 
For instance, the fact that `Projection` is a factory for …

RunningProjection and isolated internal state

---

akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala
build.sbt

I moved the current example back to the Kafka project as a integration test. I updated the increment count logic so the count occurs atomically within an update statement.  I'll add some more test cases later.
Fixes #109

Move example to Kafka project as integration test

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala
akka-projection-core/src/main/scala/akka/projection/MergeableOffset.scala
akka-projection-core/src/main/scala/akka/projection/internal/OffsetSerialization.scala
akka-projection-core/src/test/scala/akka/projection/internal/OffsetSerializationSpec.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/KafkaSourceProvider.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala
akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala
akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala
docs/src/main/paradox/eventsourced.md
docs/src/main/paradox/kafka.md
examples/src/test/java/jdocs/kafka/KafkaDocExample.java
examples/src/test/resources/logback-test.xml
examples/src/test/scala/docs/kafka/KafkaDocExample.scala
project/project-info.conf

On top of https://github.com/akka/akka-projection/pull/131
Also requires https://github.com/akka/akka-projection/pull/132 to be able to run the example.
* also moved MergableOffset to public place
I intend to add publishing to Kafka in a separate PR, and also mention committing offsets to Kafka. For the latter I guess we will just refer to Alpakka Kafka documentation since Projections is not adding any value.
References #79

reference docs for KafkaSourceProvider

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala
akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java
akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala
docs/src/main/paradox/testing.md
examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java
examples/src/test/java/jdocs/testkit/TestKitDocExample.java
examples/src/test/scala/docs/testkit/TestKitDocExample.scala

References #134 
* ensure that TestKit will stop the projection when running with `runWithTestSink`
* all methods return the type returned by the user function *
* using Akka's Functions in Java to allow for throwing exceptions
\* that change make it easier to collect that from inside the lambda and use it further in other parts of the test. Scala users can return `Unit` if they want, and life continues. For Java users, it's a little bit more verbose. If they don't want to use the value from outside, they need to explicitly return something, like `Done.getInstance()`.

TestKit API improvements

---

.travis.yml

Apparently we enabled it only for JDK8. 
Took the opportunity to bump the snapshot version as well.

Run JDK11 tests with Akka snapshot

---

akka-projection-cassandra/src/main/resources/reference.conf
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraSettings.scala
akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/ContainerSessionProvider.scala
akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala
akka-projection-slick/src/main/resources/reference.conf
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickSettings.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickOffsetStoreSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickSpec.scala
akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala
examples/src/test/scala/akka/projection/cassandra/scaladsl/WordCountDocExampleSpec.scala

References #153 and #154
On top of #180

make Cassandra keyspace, table and config path configurable

---

akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala
akka-projection-core/src/main/scala/akka/projection/internal/NoopStatusObserver.scala
akka-projection-core/src/test/scala/akka/projection/TestStatusObserver.scala
docs/src/main/paradox/management.md

rename StatusObserver.restarted to failed, #194

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala
akka-projection-core/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

* otherwise the stream would not be completed by the killSwitch until after all retries
* I considered if the abort mechanism in applyRecovery should abort immediately before
waiting until the current handler.process (or delay) call had finished (using something like firstCompletedOf),
but that would be dangerous to have an process call in flight and then a new projection instance is
started with the same handler instance and thereby causing concurrent calls
References #187

abort retries when projection is stopped, #187

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala
akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-slick/src/test/resources/logback-test.xml
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
docs/src/main/paradox/cassandra.md
docs/src/main/paradox/slick.md
examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java
examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala
examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala

On top of #118 
When adding support for grouped envelopes I realized that adding support for `Flow` is simple.
TODO:
Refs https://github.com/akka/akka-projection/issues/145

Flow as handler

---

.travis.yml
project/Dependencies.scala

Upgrades to Akka 2.6.6
This remove the need to use snapshots in the test (workaround for the logging issue).
Not removing the snapshot repository (eg: project/AkkaSnapshotRepository.scala) because this will be useful for running CRON jobs.

Upgrade to Akka 2.6.6

---

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala
akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala

Draft because on top of #210.
Ready for review otherwise.

JDBC: Enable all exactly-once tests

---

akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
docs/src/main/paradox/actor.md
docs/src/main/paradox/flow.md
docs/src/main/paradox/slick.md
examples/src/test/java/jdocs/kafka/KafkaDocExample.java
examples/src/test/scala/docs/kafka/KafkaDocExample.scala
examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala

* also use the jdbc atLeastOnceAsync in the Kafka doc sample
References #68

support Future based Handler in SlickProjection, #68

---

akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala
akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickOffsetStoreSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

This should solve some flakiness tests we observed in the JDBC tests. I hope, I think.

Use random ProjectionIds in tests

---

project/Dependencies.scala

2.13.2 had some issues (that was the reason we didn't use that in akka/akka)

Scala 2.13.3

---

.travis.yml

As seen in https://travis-ci.com/github/akka/akka-projection/jobs/355392645/config `sudo` is no longer used.

Remove unused setting

---

akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala

Remove offset check in at-least-once projections that has stream failures. 
The rationale is that we have no guarantee that an offset will be persisted. For example, if we persist every 2 elements, and element on index 3 fails. It's possible that the stream is stopped before the offset 2 is saved. 
Also remove some repetition in tests.
Based on #284 and #301

Harden at-least-once JDBC tests

---

.travis.yml
akka-projection-jdbc/src/main/resources/reference.conf
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala
akka-projection-jdbc/src/test/resources/logback-test.xml
akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala
akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

Tests are still terribly failing in Travis. 
We got another 
```
[info] - must restart from previous offset - handler throwing an exception, save after 2 *** FAILED *** (5 seconds, 118 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 18 times over 5.024763741000001 seconds. Last failure message: The Option on which value was invoked was not defined.. (JdbcProjectionSpec.scala:749)
```
see https://travis-ci.com/github/akka/akka-projection/jobs/356358520#L1021
That makes zero sense to me. 
This PR is removing all tests but the JdbcProjectionSpec at-least-once test.

More logging for JDBC operations

---

.gitignore
.travis.yml
akka-projection-slick/src/test/scala/akka/projection/slick/SlickOffsetStoreSpec.scala
project/Dependencies.scala

Adds tests for Postgres, MySQL, MS SQL Server and Oracle for the SlickOffsetStore. 
Very surprisingly, this worked on first run. I was expecting it to fail for MS Server because of differences in how the timestamp column is handled. 
I was also expecting this to fail because of #305.

Extend SlickOffsetStore tests to all supported DBs

---

akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/javadsl/KafkaSourceProvider.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/scaladsl/KafkaSourceProvider.scala
akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala
akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala

Draft because on top of #315.
Ready for review otherwise
References #316

uses a factory for  MetadataClientAdapter

---

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala
akka-projection-jdbc/src/test/scala/akka/projection/jdbc/internal/JdbcSettingsSpec.scala

References #311 
* allows the pool size to be defined with a valid string, eg: "10". 
* more clear error messages and extended tests
* allows users to step out of thread-pool-executor

JdbcSettings loading improvements

---

build.sbt

Follow up of #340 which broke `whitesourceCheckPolicies` due to sbt config scoping.
https://travis-ci.com/github/akka/akka-projection/jobs/360998973#L273
I'll be honest, I find it quite confusing myself, but I've removed most of the cross scoping which seemed to be confusing the whitesource plugin.

Config scope cleanup

---

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala
akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java
examples/src/test/java/jdocs/jdbc/JdbcHibernateTest.java

References #317
`ProjectionTestKit` still has a couple usages of Akka-custom functional interfaces:
- `akka.japi.function.Effect`, which has no JDK APi equivalent
- `akka.japi.function.Procedure` instead of `java.util.function.Consumer`. I haven't replaced this one because it is more convenient for users (`Procedure` allows users to throw exception).

Prefer JDK API over Akka-custom functional interfaces

---

akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala
akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
akka-projection-core/src/main/scala/akka/projection/internal/NoopStatusObserver.scala
akka-projection-core/src/test/scala/akka/projection/StatusObserverSpec.scala
akka-projection-core/src/test/scala/akka/projection/TestStatusObserver.scala
akka-projection-core/src/test/scala/akka/projection/internal/metrics/ServiceTimeMetricSpec.scala
akka-projection-core/src/test/scala/akka/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala
akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

References #277 
Note to reviewers: The big chunk in this PR is the test `StatusObserverSpec`. The rest is rather small and straightforward.

Fine grained envelope ops in status observer

---

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala

References #77 
I've done a review of the API doc of all other methods in `SlickProjection` and didn't find anything else missing. Also reviewed `JdbcProjection`.
I haven't made any edit or review of the `docs/`. We can address that on a separate PR.

Document transaction semantics for Slick.atLeastOnce

---

project/Dependencies.scala

The Alpakka upgrade solves the whitesource issue with `io.netty:netty-codec:4.1.39.Final`

Upgrade Akka and Alpakka

---

docs/src/main/paradox/getting-started/testing.md

Noticed that sometimes build will break when apidoc tag can't decide which variant to use.

Fix API link to ProjectionTestKit

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraSettings.scala
akka-projection-core/src/main/scala/akka/projection/HandlerRecoveryStrategy.scala
akka-projection-core/src/main/scala/akka/projection/OffsetVerification.scala
akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala
akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala
akka-projection-core/src/main/scala/akka/projection/javadsl/ActorHandler.scala
akka-projection-core/src/main/scala/akka/projection/javadsl/Projections.scala
akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala
akka-projection-core/src/main/scala/akka/projection/scaladsl/ActorHandler.scala
akka-projection-core/src/main/scala/akka/projection/scaladsl/SourceProvider.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/EventEnvelope.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/JdbcSession.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcHandler.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcHandler.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/KafkaOffsets.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/javadsl/KafkaSourceProvider.scala
akka-projection-kafka/src/main/scala/akka/projection/kafka/scaladsl/KafkaSourceProvider.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/TestProjection.scala

References #96
I focused on class-level annotations so there's probably some `private` fields/methods in publicly accessible classes that are missing `@InternalApi`.

First pass at apimaychange internalapi

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala

References #148
All DB-related operations use the `CassandraSession` so they are all run on the configured `session-dispatcher`. The `InternalProjectionState` needs an `ExecutionContext` for a handful of operations but none is DB-related. On top of that, some of the operations in `InternalProjectionState` that need an `ExecutionContext` should better not run on the DB `ExecutionContext` (e.g. `statusObserver`, `telemetry`).
Mental note (for a separate PR): should any future running `statusObserver` or `telemetry` be bound to a dedicated dispatcher?

[Cassandra] Review ExecutionContext usage - Remove FIXME

---

akka-projection-kafka/src/main/resources/reference.conf
docs/src/main/paradox/kafka.md

Document caveats when using exactly-once with Kafka source

---

akka-projection-core/src/main/scala/akka/projection/javadsl/Handler.scala
akka-projection-core/src/main/scala/akka/projection/scaladsl/ProjectionManagement.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcHandler.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/TestProjection.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala

References #96
In #359 I focused on class-level annotation. Here I'm digging deeper. I'm reviewing 3 types of cases:
- use of `@InternalApi` in scaladsl is not necessary so I removed it.
- missing use of `@InternalApi` in javadsl
- missing use of `@InternalApi` in non-API especific, non-internal code.

Review API applying InternalApi annotations and comment

---

docs/src/main/paradox/getting-started/running.md
examples/src/test/scala/docs/guide/EventGeneratorApp.scala
examples/src/test/scala/docs/guide/ShoppingCartApp.scala

I found a [comment from Patrik](https://github.com/akka/akka-projection/pull/270#discussion_r445370557) on the original Getting Started Guide that I think it makes sense. 
Basically, it's about starting with one tag like is usually done in Akka (pre-Lagom) and then, when we introduce `ShardedDaemonProcess` we can create sharded tags and explain why. 
We do have a single tag now, but we moved from one suffixed with `-eu`, giving the impression that it was about a datacenter, to one suffixed with `-001`. 
This PR changes the tag to `shopping-cart`.

Use single tag in Getting Started Guide

---

docs/src/main/paradox/kafka.md
examples/src/test/java/jdocs/jdbc/HibernateJdbcSession.java
examples/src/test/java/jdocs/kafka/KafkaDocExample.java
examples/src/test/scala/docs/kafka/KafkaDocExample.scala

References #256
Copies the approach used in JDBC/Slick pages were the actual repository implementation is left out of the sample code/docs.

Use a JDBC-backed handler to demo exactly-once

---

akka-projection-core-test/src/test/resources/logback-test.xml
akka-projection-core-test/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala
akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/TestProjection.scala
akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala
build.sbt
examples/src/test/scala/docs/guide/ShoppingCartAppSpec.scala
examples/src/test/scala/docs/kafka/KafkaDocExample.scala

* Replaces several internal `TestProjection` implementations in tests.
* New sub-project `akka-projection-core-test` was created so that `ProjectionBehaviorSpec` could reference the testkit.  Should we move all core tests here?
* Incremental development of `TestProjection` in testkit to be cleaned up for external usage in #198
TODO
- See #381

DRY TestProjection usages for internal tests

---

.travis.yml
akka-projection-core-test/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestProjectionImpl.scala

Fixes https://github.com/akka/akka-projection/issues/393
Corrected source stream initialization in test projection used by `ProjectionBehaviorSpec`

ProjectionTestBehaviorSpec lifecycle fix

---

examples/src/test/java/jdocs/guide/ShoppingCartAppTest.java
examples/src/test/scala/docs/guide/ShoppingCartAppSpec.scala

Generate integers 0..9 for test so that slow execution can't cause an 11th message to be logged for test assertion.
Noticed the failure here:
https://travis-ci.com/github/akka/akka-projection/jobs/378449397#L650

Guide ShoppingCartTest/Spec log test 0 until 9

---

akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestProjectionImpl.scala
akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/TestProjectionSpec.scala

Fixes #416 
The test may be overkill, but since we missed this use case before I think it's a good idea.  The `ActorHandler` impl could be simplified down to few lines of code.  We may want to add tests for the other handlers too, though they're mostly covered by the rest of the project testsuite.

Implement actorinit in TestProjection

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
docs/src/main/paradox/cassandra.md
docs/src/main/paradox/jdbc.md
docs/src/main/paradox/slick.md

As mentioned in #405, this method were not properly documented.

Document createOffsetTableIfNotExists method

---

akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala

* Eventually assert partial projection consumption (should fix #458)
* Assert an `Option` where the assertion isn't retried by the projection test kit or using ScalaTest

Assert Option where assertion not retried

---

akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java

Fixes #397
My suspicion is that #397 is caused by a race condition where the string builder assertion of current state passes, but the next envelope to generate the exception has not yet been processed. This change will assert the error event from the stream directly using a probe.

Wait for onError stream event

---

akka-projection-kafka/src/it/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala

The test didn't publish any new events to the topic after the second start. I wanted to verify that the offset tracking was working for KafkaSourceProvider since that was discussed in https://github.com/akka/akka-projection/pull/424

improve test resume in KafkaToSlickIntegrationSpec

---

akka-projection-cassandra/src/main/mima-filters/1.0.0.backwards.excludes/akka-2.6.10.excludes
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
akka-projection-core/src/main/mima-filters/1.0.0.backwards.excludes/akka-2.6.10.excludes
akka-projection-core/src/main/scala/akka/projection/Projection.scala
akka-projection-core/src/main/scala/akka/projection/internal/ProjectionSettings.scala
akka-projection-jdbc/src/main/mima-filters/1.0.0.backwards.excludes/akka-2.6.10.excludes
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala
akka-projection-slick/src/main/mima-filters/1.0.0.backwards.excludes/akka-2.6.10.excludes
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
akka-projection-testkit/src/main/mima-filters/1.0.0.backwards.excludes/akka-2.6.10.excludes
akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestProjectionImpl.scala
project/Dependencies.scala

The reason for updating is the incompatibility in the TestKit as described in the issue https://github.com/akka/akka-projection/issues/466
Also changed internals to use the new `akka.stream.RestartSettings`. Old signature was deprecated. 
References #466

Akka 2.6.10, and use akka.stream.RestartSettings, #466

---

.gitignore
akka-projection-cassandra/src/it/scala/akka/projection/cassandra/ContainerSessionProvider.scala
akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcContainerOffsetStoreSpec.scala
akka-projection-kafka/src/it/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala
akka-projection-kafka/src/it/scala/akka/projection/kafka/KafkaSpecBase.scala
akka-projection-kafka/src/it/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala
akka-projection-slick/src/it/scala/akka/projection/slick/SlickContainerOffsetStoreSpec.scala
container-license-acceptance.txt
project/Dependencies.scala

Older `confluentinc/cp-kafka` docker images have been removed from DockerHub. I assume in response to new space-related policies. Confluent made structural changes to `cp-kafka` images as of Apache Kafka 2.5.0 (CP 5.5.0) that were backported to patch releases of older `cp-kafka` images, breaking compatibility with testcontainers readiness and start scripts.
This PR will get tests working again by using the latest Alpakka Kafka milestone release, but we should wait for a final artifact of Alpakka Kafka 2.0.x or 2.1.0 before releasing projections.

Bump alpakka-kafka to fix cp-kafka image changes

---

project/Dependencies.scala

This should reduce the number of cluster startup timeouts and let us change them if necessary.

Alpakka Kafka 2.0.7

---

.github/workflows/checks.yml
.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml
.travis.yml
akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcContainerOffsetStoreSpec.scala
akka-projection-slick/src/it/scala/akka/projection/slick/SlickContainerOffsetStoreSpec.scala
scripts/cat-log.sh

Moves Akka Projection to GitHub Actions, mainly because we have experienced issues with docker and travis. 
The travis job have two snapshots variables (`$AKKA_SNAPSHOT` and `$ALPAKKA_KAFKA_SNAPSHOT`) but they were not being set. We probably want to do something about it. Maybe on another PR later.

Moving to GitHub Actions

---

akka-projection-core-test/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala
akka-projection-core/src/main/resources/reference.conf
akka-projection-core/src/main/scala/akka/projection/scaladsl/ProjectionManagement.scala
akka-projection-kafka/src/it/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala

* because of race condition of topic registration and early management operation
* also problem in cluster when publish happens before subscribers are know
References #531

Retry management operations if timeout, #531

---

akka-projection-jdbc/src/main/mima-filters/1.1.0.backwards.excludes/jdbc-settings.excludes
akka-projection-jdbc/src/main/resources/reference.conf
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala
akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java
examples/src/test/java/jdocs/jdbc/HibernateJdbcSession.java

Main reason: we using Play [JPAApi](https://www.playframework.com/documentation/2.8.x/JavaJPA#Using-play.db.jpa.JPAApi) and already have a dispatcher ([Using a CustomExecutionContext](https://www.playframework.com/documentation/2.8.x/JavaJPA#Using-a-CustomExecutionContext)). 
It will be good if we can sharing exist connection pool and dispatcher for Akka Projection.

Configurable path of dispatcher for JDBC projections

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala
akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala
akka-projection-kafka/src/it/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala
akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
docs/src/main/paradox/cassandra.md
docs/src/main/paradox/jdbc.md
docs/src/main/paradox/slick.md
examples/src/it/java/jdocs/cassandra/WordCountDocExampleTest.java
examples/src/it/scala/docs/cassandra/WordCountDocExampleSpec.scala
examples/src/test/scala/docs/kafka/KafkaDocExample.scala

* because creating management table also
* old methods remains as deprecated

rename createOffsetTableIfNotExists and dropOffsetTableIfExists

---

project/Dependencies.scala

* Jackson 2.11.4 is the reason
* since we are anyway releasing a minor version it's good to include this bump

Akka 2.6.14 and Jackson 2.11.4

---

build.sbt
project/Common.scala

* in ThisBuild didn't play with the AutoPlugin
* now confirmed with `show sonatypeProfileName`

sonatypeProfileName in projectSettings

---

project/Common.scala

Seems to work without this, but I think this is more correct. Original suggestion from @2m in https://gitter.im/sbt/sbt?at=5a4ed1abba39a53f1ad9a1fb

add CiReleasePlugin to requires in Common

---

akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestOffsetStoreAdapter.scala
project/AkkaDisciplinePlugin.scala
project/Dependencies.scala

This is in preparation for compiling with Scala 3. 
There is no plugin for scala 3 and it doesn't make sense to continue use it, because...
1. we should use Scala's @nowarn
2. the only place we used is better solved by using `"org.scala-lang.modules" %% "scala-collection-compat"`, which is now introduced in this PR.

fix: remove silencer plugin

---

build.sbt

Current links in docs are poing to https://github.com/akka/akka-projection.git, should be https://github.com/akka/akka-projection

fix github.base_url

---

akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala

* EventTimestampQuery and LoadEventQuery are optional
* if the offset is not TimestampOffset (and depending on
offset store) those are not needed
* e.g. in a testkit

Remove fail fast check in EventsBySlicesSourceProvider

---

akka-projection-core-test/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala
akka-projection-core/src/main/mima-filters/1.2.3.backwards.excludes/skip-offset.excludes
akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala
akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala

* need this to be able to fix one of the pending tests in akka-persistence-r2dbc
* makes more sense to try to store the offset when an envelope is skipped

Store offset for failed skipped envelope

---

akka-projection-grpc/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala

Compilation error in `main` due to concurrent PR merges.

One more TestSink

---

akka-projection-grpc/src/it/scala/akka/projection/grpc/IntegrationSpec.scala
akka-projection-grpc/src/it/scala/akka/projection/grpc/consumer/scaladsl/EventTimestampQuerySpec.scala
akka-projection-grpc/src/it/scala/akka/projection/grpc/consumer/scaladsl/LoadEventQuerySpec.scala
akka-projection-grpc/src/main/resources/reference.conf
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/GrpcQuerySettings.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/GrpcReadJournalProvider.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventProducerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtoAnySerialization.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducer.scala
akka-projection-grpc/src/test/protobuf/akka/projection/grpc/internal/shoppingcart_api.proto
akka-projection-grpc/src/test/scala/akka/projection/grpc/consumer/GrpcQuerySettingsSpec.scala
akka-projection-grpc/src/test/scala/akka/projection/grpc/internal/ProtoAnySerializationSpec.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestOffsetStoreAdapter.scala
docs/src/main/paradox/grpc.md
samples/grpc/shopping-analytics-service-java/pom.xml
samples/grpc/shopping-analytics-service-java/src/main/java/shopping/analytics/ShoppingCartEventConsumer.java
samples/grpc/shopping-analytics-service-java/src/main/resources/grpc.conf
samples/grpc/shopping-analytics-service-scala/build.sbt
samples/grpc/shopping-analytics-service-scala/src/main/resources/grpc.conf
samples/grpc/shopping-analytics-service-scala/src/main/scala/shopping/analytics/ShoppingCartEventConsumer.scala
samples/grpc/shopping-cart-service-scala/build.sbt

* Incorporated from Kalix JVM SDK, with some refactoring and removal of not needed stuff
* Use protobuf descriptors instead of defining mapping in configuration.
* Update samples
* Update documentation
References #698

Register protobuf message descriptors for deserialization, #698

---

akka-projection-grpc/src/it/scala/akka/projection/grpc/IntegrationSpec.scala
akka-projection-grpc/src/it/scala/akka/projection/grpc/consumer/scaladsl/EventTimestampQuerySpec.scala
akka-projection-grpc/src/it/scala/akka/projection/grpc/consumer/scaladsl/LoadEventQuerySpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/GrpcQuerySettings.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/test/java/akka/projection/grpc/consumer/javadsl/ConsumerCompileTest.java
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala
samples/grpc/shopping-analytics-service-java/src/main/java/shopping/analytics/ShoppingCartEventConsumer.java
samples/grpc/shopping-analytics-service-scala/src/main/scala/shopping/analytics/ShoppingCartEventConsumer.scala

* withAdditionalRequestMetadata for optional metadata 
* Convenience factory methods for GrpcReadJournal
Draft because on top of other PR, but otherwise ready for review.
Refs #703

Improve ergonomics of creating GrpcReadJournal, #703

---

project/Dependencies.scala

Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-42003 (even if we were not really affected out of the box).

chore: Bump Jackson databind

---

.github/workflows/fossa.yml

The Fossa CLI installation was outdated.
Changed to `coursier/setup-action` for the JDK and sbt installation.

chore: modern Fossa workflow

---

.github/workflows/checks.yml
.github/workflows/fossa.yml
.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-grpc.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml

- Current versions of GH actions.
- Use coursier setup-action
- Add JDK17 to the matrices.
Notice: release runs on JDK 8
Aligns with
- https://github.com/akka/akka/pull/31730
- https://github.com/akka/akka/pull/31734

ci: renovate GH workflows; JDK 17

---

akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala

Failing all over the place, probably a race in the test somehow.
References #641

fix: Disable flaky Kafka test for now #641

---

docs/src/main/paradox/cassandra.md
docs/src/main/paradox/jdbc.md
docs/src/main/paradox/running.md
docs/src/main/paradox/slick.md

The plugin never reached a final release and is no longer available
References #774

doc: Remove mentions of spanner

---

akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
project/Common.scala

References #643
Ordering issue, the test expected that offsets writing was always completed when the next envelope is processed. Throwing in the event handler can overtake the write since it is run in a stream and errors tearing down the stream is not ordered.
A `delay(100.millis)` between the `atLeastOnceHandlerFlow` and the downstream ending in offset commit confirms the suspicion by failing the test cases exercising failure 
* Bonus: added stack traces to integration test failures.

fix: CassandraProjectionSpec race conditions

---

akka-projection-grpc/src/test/java/akka/projection/grpc/replication/javdsl/ReplicationCompileTest.java
akka-projection-grpc/src/test/scala/akka/projection/grpc/replication/scaladsl/ProducerApiSample.scala
docs/src/main/paradox/grpc-replicated-event-sourcing-transport.md

doc: Replicated event sourcing gRPC doc improvements

---

build.sbt
docs/src/main/paradox/getting-started/index.md
docs/src/main/paradox/grpc.md
docs/src/main/paradox/slick.md
project/Dependencies.scala
project/build.properties
project/plugins.sbt
samples/grpc/shopping-analytics-service-java/pom.xml
samples/grpc/shopping-analytics-service-scala/project/build.properties
samples/grpc/shopping-analytics-service-scala/project/plugins.sbt
samples/grpc/shopping-cart-service-java/pom.xml
samples/grpc/shopping-cart-service-scala/project/build.properties
samples/grpc/shopping-cart-service-scala/project/plugins.sbt
samples/replicated/shopping-cart-service-java/pom.xml
samples/replicated/shopping-cart-service-scala/project/build.properties
samples/replicated/shopping-cart-service-scala/project/plugins.sbt
scripts/link-validator.conf

Makes the Scala XML 2.1 jump in sbt.
References
- https://github.com/sbt/sbt/releases/tag/v1.8.2
- https://github.com/akka/akka/releases/tag/v2.8.0-M4
- https://github.com/akka/akka-grpc/releases/tag/v2.3.0-M2
- https://github.com/sbt/sbt-site/releases/tag/v1.5.0-RC2
Alpakka milestone pending.
The link checker is much happier than before.
I'm not sure we need all of this now.

bump: Akka 23.02 milestones; sbt bumps

---

.github/workflows/dependency-submission.yml

Use Scala Center's action to report sbt dependencies to the GitHub API.

chore: dependency submission to GitHub

---

akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/replication/ReplicationIntegrationSpec.scala
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/replication/ReplicationJavaDSLIntegrationSpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/internal/ReplicationImpl.scala

* using the Projection Stop message
* but then in some restart backoff situations it will take a while for the projections to terminate gracefully
* reduce handoff timeout so that rebalance is not delayed for too long
At first I suspected that RestartSource wouldn't stop by the killswitch when it was in backoff, but I verified that in an Akka unit test. Not sure what is causing the delays but this is probably good enough (for now).
References #777

fix: reduce handoff timeout for RES projections, #777

---

akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
project/Dependencies.scala

This came up during the scala3 builds, and it seemed enough of a change to make it separate. I did not investigate why that needs changed though.

chore: bump scalaTest,scalatestplus and fix tests

---

.github/workflows/checks.yml
akka-projection-core-test/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala
akka-projection-core-test/src/test/scala/akka/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala
akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala
akka-projection-core/src/main/scala/akka/projection/ProjectionId.scala
akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
akka-projection-core/src/main/scala/akka/projection/internal/ProjectionContextImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/GrpcReadJournalProvider.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtoAnySerialization.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/javadsl/Replication.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/javadsl/ReplicationSettings.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/scaladsl/ReplicationSettings.scala
akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestProjectionImpl.scala
build.sbt
project/Common.scala
project/Dependencies.scala
project/Scala3.scala

The following modules are published for scala3 now:
- `akka-projection-core`
- `akka-projection-testkit`
- `akka-projection-eventsourced`
- `akka-projection-kafka`
- `akka-projection-durable-state`
- `akka-projection-grpc`

Scala3 builds

---

.github/workflows/dependency-submission.yml

Apparently even Scala tool dependencies are submitted.
See 
- https://github.com/scalacenter/sbt-dependency-submission/issues/49#issuecomment-1373614001
References 
- #792 
- #802

chore: exclude tooling from dependency graph submission

---

akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
project/Dependencies.scala

- Bump the H2 driver used in tests.
References 
- #668

bump: h2 2.1.214 (was 1.4.200)

---

akka-projection-grpc-tests/src/it/resources/logback-test.xml
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/IntegrationSpec.scala
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/TestData.scala
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/consumer/scaladsl/EventTimestampQuerySpec.scala
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/consumer/scaladsl/LoadEventQuerySpec.scala
akka-projection-grpc-tests/src/test/java/akka/projection/grpc/consumer/javadsl/ConsumerCompileTest.java
akka-projection-grpc-tests/src/test/java/akka/projection/grpc/producer/javadsl/ProducerCompileTest.java
akka-projection-grpc-tests/src/test/java/akka/projection/grpc/replication/javdsl/ReplicationCompileTest.java
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/ConsumerFilterSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ConsumerFilterRegistrySpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ConsumerFilterStoreSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ProtoAnySerializationSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/TestData.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/ConsumerFilter.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerFilterRegistry.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerFilterStore.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala

* When a filter is added via the ConsumerFilter extension it should be propagated to other streams with the same streamId, also other nodes in the (consumer side) cluster, and FilterReq submitted to each stream. The filter state must also be “stored” so that it can be retrieved when a new stream is started.
* This adds local alternative, when cluster isn't used on the consumer side.
* ddata implemenation will come in separate PR.

feat: Store consumer filter

---

.scala-steward.conf
project/Dependencies.scala
samples/grpc/shopping-analytics-service-java/pom.xml
samples/grpc/shopping-analytics-service-scala/build.sbt
samples/grpc/shopping-cart-service-java/pom.xml
samples/grpc/shopping-cart-service-scala/build.sbt
samples/replicated/shopping-cart-service-java/pom.xml
samples/replicated/shopping-cart-service-scala/build.sbt

bump(tests): logback 1.3.6 (was 1.2.11) and lock minor version

---

akka-projection-core/src/main/scala/akka/projection/internal/CanTriggerReplay.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/IntegrationSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/ConsumerFilter.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/internal/ReplicationImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/javadsl/Replication.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/scaladsl/Replication.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
samples/grpc/shopping-analytics-service-scala/README.md
samples/grpc/shopping-cart-service-scala/README.md
samples/grpc/shopping-cart-service-scala/src/main/scala/shopping/cart/ShoppingCart.scala
samples/replicated/shopping-cart-service-scala/README.md
samples/replicated/shopping-cart-service-scala/build.sbt
samples/replicated/shopping-cart-service-scala/src/main/protobuf/ShoppingCartService.proto
samples/replicated/shopping-cart-service-scala/src/main/scala/shopping/cart/ShoppingCart.scala
samples/replicated/shopping-cart-service-scala/src/main/scala/shopping/cart/ShoppingCartServiceImpl.scala

* api for producerFilter for Replicated Event Sourcing
* requests must include replicaId
* updated sample with producer and consumer filters

feat: producer and consumer filters for Replicated Event Sourcing

---

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala

* optimization to avoid fruitless replay queries that are for another RES replica

perf: avoid replay requests for another replica

---

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/ConsumerFilterSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ConsumerFilterStoreSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ConsumerSerializerSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/consumer.proto
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/ConsumerFilter.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerFilterStore.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerSerializer.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala

* following the same pattern as the other consumer filters
* exclude tags
* remove exclude tags
* include tags
* remove include tags
* when a new entity is "activated" via a tag that will trigger a replay because the offset store doesn't accept unknown/unexpected sequence number (same mechanism as we have for the producer filters)

feat: consumer filter with tags

---

akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/ConsumerFilter.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
docs/src/main/paradox/grpc-replicated-event-sourcing-transport.md
docs/src/main/paradox/grpc.md
samples/grpc/shopping-analytics-service-java/src/main/java/shopping/analytics/ShoppingCartEventConsumer.java
samples/grpc/shopping-analytics-service-scala/README.md
samples/grpc/shopping-analytics-service-scala/build.sbt
samples/grpc/shopping-analytics-service-scala/src/main/protobuf/ShoppingCartEvents.proto
samples/grpc/shopping-analytics-service-scala/src/main/scala/shopping/analytics/Main.scala
samples/grpc/shopping-analytics-service-scala/src/main/scala/shopping/analytics/ShoppingCartEventConsumer.scala
samples/grpc/shopping-cart-service-java/src/main/java/shopping/cart/PublishEvents.java
samples/grpc/shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCart.java
samples/grpc/shopping-cart-service-scala/README.md
samples/grpc/shopping-cart-service-scala/src/main/protobuf/ShoppingCartEvents.proto
samples/grpc/shopping-cart-service-scala/src/main/protobuf/ShoppingCartService.proto
samples/grpc/shopping-cart-service-scala/src/main/scala/shopping/cart/PublishEvents.scala
samples/grpc/shopping-cart-service-scala/src/main/scala/shopping/cart/ShoppingCart.scala
samples/grpc/shopping-cart-service-scala/src/main/scala/shopping/cart/ShoppingCartServiceImpl.scala

* simplified the consumer side filter sample to also use tags
Not all Java snippets are updated yet. The Java samples are more difficult to update because they use the bom dependencies. We'll make a separate round with the Java samples.

doc: Reference docs of filters

---

akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/resources/reference.conf
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala

* the r2dbc statement.add() will still result in one round trip to the db for each added statement
* using Postgres insert with many values instead
* grouped into batches of 20, and remaining executed as before
References #897

perf: More efficient batch insert of offsets, #897

---

akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
akka-projection-core/src/main/scala/akka/projection/internal/OffsetStrategy.scala
akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala

* Issue for R2dbcProjection.groupedWithinAsync, which only stored the last offset of the group
* Symptom was Rejected envelope from backtracking after restarting
* Store all offset of the group
* Easiest to not use the AtLeastOnce offsetStrategy for this and instead store the offset in the handler adapter, which is very similar to grouped ExactlyOnce
* This might be a slight change in semantics in the way that start processing of next group will not begin until offsets for previous group has been stored. I think that is totally fine, and it was only 1 group in flight previously.
References #906

fix: Store all grouped offsets for R2DBC, #906

---

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala
build.sbt
project/Dependencies.scala

Bumps Alpakka to 6.0.1 and adds Scala3 support to cassandra

feat: cassandra cross build for Scala 3

---

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventProducerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducer.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducer.scala

* the lazy replay requests in Projections over gRPC can start from snapshots to reduce number of events to load and transfer
On top of https://github.com/akka/akka-projection/pull/929
See https://github.com/akka/akka-persistence-r2dbc/pull/412

feat: Snapshot as starting point for replay

---

akka-distributed-cluster-docs/src/main/paradox/guide/2-service-to-service.md
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/producer/TopicProducerFilterEndToEndSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/ConsumerFilterSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ConsumerSerializerSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/TopicMatcherSpec.scala
akka-projection-grpc/src/main/mima-filters/1.4.2.backwards.excludes/topic-filter.excludes
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/consumer.proto
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/resources/reference.conf
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/ConsumerFilter.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerFilterStore.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerSerializer.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventProducerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/TopicMatcher.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/EventProducerSettings.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducerSource.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducer.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/javadsl/Replication.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/scaladsl/Replication.scala
docs/src/main/paradox/grpc.md

* same syntax and semantics of wildcard filters as MQTT
- single level wildcard '+'
- multi level wildcard at the end '#'
* topic for entity is defined by and ordinary event tag with a 't:' prefix
- prefix is configurable
* follows same pattern as other filters
- rather mechanical addition similar to IncludeTags
TODO:

feat: Topic filters for Projections over gRPC

---

docs/src/main/paradox/cassandra.md
docs/src/main/paradox/durable-state.md
docs/src/main/paradox/eventsourced.md
docs/src/main/paradox/getting-started/setup-your-app.md
docs/src/main/paradox/grpc-replicated-event-sourcing-transport.md
docs/src/main/paradox/grpc.md
docs/src/main/paradox/jdbc.md
docs/src/main/paradox/kafka.md
docs/src/main/paradox/r2dbc.md
docs/src/main/paradox/running.md
docs/src/main/paradox/slick.md
docs/src/main/paradox/testing.md
project/plugins.sbt

@ennru I haven't added the repository information in all places where we use `@@dependency` directive. Only in cases where it makes sense from my perspective, but maybe I missed sth.

docs: add repository info

---

akka-distributed-cluster-docs/src/main/paradox/guide/1-event-sourced-shopping-cart.md
akka-distributed-cluster-docs/src/main/paradox/guide/2-service-to-service.md
akka-distributed-cluster-docs/src/main/paradox/guide/3-active-active.md
samples/grpc/shopping-analytics-service-java/README.md
samples/grpc/shopping-analytics-service-scala/README.md
samples/grpc/shopping-cart-service-java/README.md
samples/grpc/shopping-cart-service-scala/README.md
samples/replicated/shopping-cart-service-java/README.md
samples/replicated/shopping-cart-service-scala/README.md

Follow up on https://github.com/akka/akka-projection/pull/890

chore: A few more docker-compose

---

akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/producer/EventProducerPushSpec.scala
akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/producer/ProducerPushSample.scala
akka-projection-grpc-tests/src/test/java/akka/projection/grpc/consumer/javadsl/EventProducerPushDestinationCompileTest.java
akka-projection-grpc/src/main/mima-filters/1.5.0-M2.backwards.excludes/event-producer-push-protobuf.excludes
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventPusherConsumerServiceImpl.scala
docs/src/main/paradox/grpc-producer-push.md
samples/grpc/local-drone-control-scala/project/build.properties
samples/grpc/restaurant-drone-deliveries-service-scala/project/build.properties

Before this the producer push spec was relying on Akka serialisation format for the payloads, but to use protobuf messages (which I think is what we should recommend for decoupling) as wire protocol we need to be able to pass along protobuf descriptors for the messages.
Added minimal docs, not sure, but perhaps we need something more fleshed out?

fix: Allow passing protobuf descriptors to producer push consumer

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/Transformation.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventProducerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventPusherConsumerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/Transformation.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducer.scala
docs/src/main/paradox/grpc-producer-push.md
docs/src/main/paradox/grpc.md

chore: Transformation.identity vs empty

---

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/consumer/javadsl/EventProducerPushDestinationSpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/EventProducerPushDestination.scala

Incorrect adaptation of Akka gRPC Java DSL metadata

fix: Java ProducerPushDestination transformation and interceptor broken

---

akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/producer/EventProducerPushSpec.scala
akka-projection-grpc-tests/src/test/java/akka/projection/grpc/producer/javadsl/ProducerCompileTest.java
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/producer/scaladsl/TransformationSpec.scala
akka-projection-grpc/src/main/mima-filters/1.5.0-M3.backwards.excludes/producer-transform-filter.excludes
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/Transformation.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/Transformation.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducer.scala

Pretty common to want to transform envelope to outgoing representation without any async (noticed in sample projects)

feat: One more convenient/common producer transform signature

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConnectionException.scala

There is something more spewing out a full stack trace but didn't figure out what yet.

chore: A bit less noise on gRPC journal client fail/reconnect

---

samples/grpc/iot-service-scala/README.md
samples/grpc/iot-service-scala/src/main/protobuf/iot/registration/RegistrationEvents.proto
samples/grpc/iot-service-scala/src/main/protobuf/iot/registration/RegistrationService.proto
samples/grpc/iot-service-scala/src/main/protobuf/iot/registration/SensorTwinService.proto
samples/grpc/iot-service-scala/src/main/protobuf/iot/registration/TemperatureEvents.proto
samples/grpc/iot-service-scala/src/main/scala/iot/registration/Registration.scala
samples/grpc/iot-service-scala/src/main/scala/iot/registration/RegistrationEvents.scala
samples/grpc/iot-service-scala/src/main/scala/iot/registration/RegistrationServiceImpl.scala
samples/grpc/iot-service-scala/src/main/scala/iot/temperature/SensorTwin.scala
samples/grpc/iot-service-scala/src/main/scala/iot/temperature/SensorTwinServiceImpl.scala
samples/grpc/iot-service-scala/src/main/scala/iot/temperature/TemperatureEvents.scala
samples/grpc/iot-service-scala/src/test/scala/iot/EdgeApp.scala

* Learned from domain expert that sensor id (DevEUI) should not be used as entityId.
* To not convolute the sample we just skip the sensor id.

chore: remove sensorId

---

akka-projection-grpc-tests/src/test/java/akka/projection/grpc/consumer/javadsl/EventProducerPushDestinationCompileTest.java
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/ProtoAnySerializationSpec.scala
akka-projection-grpc/src/main/mima-filters/1.5.0-M3.backwards.excludes/SerializedEvent.excludes
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/Transformation.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventPusherConsumerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtoAnySerialization.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtobufProtocolConversions.scala

See https://github.com/akka/akka/pull/32068 and https://github.com/akka/akka-persistence-r2dbc/pull/441

perf: Avoid event serialization in producer push destination

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala

Turns out creating it with GrpcClientSettings just to be able to specify settings was messy.

chore: More factory overloads for grpc read journal

---

akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtobufProtocolConversions.scala

* If empty it is assumed to be the persistence_id -> seq_nr of enclosing Event or FilteredEvent
* Populated when creating the TimestampOffset

chore: Make seen optional in proto Offset

---

akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java
akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala
akka-projection-slick/src/main/resources/reference.conf
akka-projection-slick/src/test/scala/akka/projection/slick/SlickOffsetStoreSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
examples/src/test/java/jdocs/jdbc/JdbcProjectionDocExample.java
examples/src/test/resources/META-INF/persistence.xml
examples/src/test/scala/docs/jdbc/JdbcProjectionDocExample.scala

* workaround for H2 bug, see https://github.com/akka/akka-projection/issues/992

test: Disable OPTIMIZE_REUSE_RESULTS

---

.gitignore
akka-edge-docs/src/main/paradox/feature-summary.md
akka-edge-docs/src/main/paradox/guide.md

As edge scenarios can have non-database storage, this commit generalises some of those references.

Generalise for more edge

---

samples/grpc/local-drone-control-scala/build.sbt
samples/grpc/local-drone-control-scala/native-image/Dockerfile
samples/grpc/local-drone-control-scala/native-image/README.md
samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/generated/reflect-config.json
samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/generated/resource-config.json
samples/grpc/local-drone-control-scala/src/main/scala/local/drones/Coordinates.scala
samples/grpc/local-drone-control-scala/src/main/scala/local/drones/DeliveriesQueue.scala

Update native image build for local-drone-control-scala to support the clustered variant.
More reflection config generated using the native image tracing agent.
Add missing CborSerializable markers for reply messages (now serialized if sending requests through a different node).
Will probably still need some more config for running in Kubernetes.

sample: update native image for clustered local-drone-control-scala

---

samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/com.typesafe.config/resource-config.json
samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/generated/jni-config.json
samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/generated/reflect-config.json
samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/generated/resource-config.json
samples/grpc/local-drone-control-scala/src/main/resources/application-kubernetes.conf
samples/grpc/local-drone-control-scala/src/main/resources/application.conf
samples/grpc/local-drone-control-scala/src/main/resources/cluster.conf
samples/grpc/local-drone-control-scala/src/main/resources/grpc.conf
samples/grpc/local-drone-control-scala/src/main/resources/local-shared.conf
samples/grpc/local-drone-control-scala/src/main/resources/postgres.conf
samples/grpc/local-drone-control-scala/src/main/resources/prod.conf

Update local-drone-control config to run in kubernetes. Run with the native image tracing agent to generate updated native image config. Tested with k3s.

sample: update local-drone-control-scala for kubernetes

---

akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/ChangeSliceRangesSpec.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedChaosSpec.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedPubSubSpec.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/OffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/PostgresOffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

* start from earliest slice when projection key is changed
New iteration of https://github.com/akka/akka-projection/pull/995 and https://github.com/akka/akka-projection/pull/1004

fix: Start from earliest slice for downscaling scenario

---

akka-edge-docs/src/main/paradox/guide/5-deploying-the-services.md
samples/grpc/local-drone-control-java/kubernetes/deployment.yml
samples/grpc/local-drone-control-java/native-image/Dockerfile
samples/grpc/local-drone-control-java/native-image/README.md
samples/grpc/local-drone-control-java/pom.xml
samples/grpc/local-drone-control-java/src/main/java/local/drones/DeliveriesQueue.java
samples/grpc/local-drone-control-java/src/main/java/local/drones/Drone.java
samples/grpc/local-drone-control-java/src/main/java/local/drones/Position.java
samples/grpc/local-drone-control-java/src/main/resources/META-INF/native-image/com.typesafe.config/resource-config.json
samples/grpc/local-drone-control-java/src/main/resources/META-INF/native-image/generated/jni-config.json
samples/grpc/local-drone-control-java/src/main/resources/META-INF/native-image/generated/reflect-config.json
samples/grpc/local-drone-control-java/src/main/resources/META-INF/native-image/generated/resource-config.json
samples/grpc/local-drone-control-scala/kubernetes/deployment.yml
samples/grpc/local-drone-control-scala/src/main/resources/META-INF/native-image/generated/resource-config.json

Update native image build for local-drone-control-java to support the clustered version and running in kubernetes. And some related small fixes.

sample: update native image for clustered local-drone-control-java

---

akka-edge-docs/src/main/paradox/feature-summary.md
akka-edge-docs/src/main/paradox/index.md
akka-edge-docs/src/main/paradox/lightweight-deployments.md

First pass on some Akka Edge docs for what I'm calling "lightweight deployments" — covering lightweight kubernetes, OpenJ9, GraalVM native image, and multidimensional autoscaling.

docs: lightweight deployments for akka edge

---

akka-edge-docs/src/main/paradox/lightweight-deployments.md

Link to some of the cloud provider products for edge environments, under the lightweight deployments section.

docs: mention some cloud provider edge environments

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducerPush.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducerSource.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducer.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducerPush.scala

* unfortunate, but EventProducerSource is shared between the two cases, and not easy to change that

chore: EventProducerSource.withStartingFromSnapshots and EventProducerPush

---

akka-edge-docs/src/main/paradox/guide/2-drone-location-to-cloud-service.md
samples/grpc/local-drone-control-java/src/main/java/local/drones/Drone.java
samples/grpc/local-drone-control-java/src/main/java/local/drones/DroneEvents.java
samples/grpc/local-drone-control-java/src/main/resources/persistence-h2.conf
samples/grpc/local-drone-control-java/src/main/resources/persistence-postgres.conf
samples/grpc/local-drone-control-scala/src/main/resources/persistence-h2.conf
samples/grpc/local-drone-control-scala/src/main/resources/persistence-postgres.conf
samples/grpc/local-drone-control-scala/src/main/scala/local/drones/Drone.scala
samples/grpc/local-drone-control-scala/src/main/scala/local/drones/DroneEvents.scala

Depends on #1047 and event writer fix P is working on over in Akka
Depends on https://github.com/akka/akka-projection/pull/1048

docs: Start from snapshot for drone push projection

---

.github/workflows/unit-tests.yml

Didn't want to go all the way with the integration tests since those are so flakey and another matrix entry for them is another chance they'll fail on every push...

build: Run unit tests on JDK 21 

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/internal/ReplicationImpl.scala

I ran into this when I had a mistake in the self-replica-id config

chore: More detailed error message for invalid replica config

---

samples/grpc/shopping-analytics-service-java/src/main/resources/persistence.conf
samples/grpc/shopping-analytics-service-scala/src/main/resources/persistence.conf
samples/grpc/shopping-analytics-service-scala/src/main/resources/serialization.conf
samples/grpc/shopping-cart-service-java/src/main/resources/persistence.conf
samples/grpc/shopping-cart-service-scala/src/main/resources/persistence.conf
samples/replicated/shopping-cart-service-java/src/main/resources/persistence.conf
samples/replicated/shopping-cart-service-scala/src/main/resources/persistence.conf

* seems we forgot to update these

sample: Dialect config in samples

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/EventProducerPushDestination.scala

* that is what it is in scaladsl

fix: Default Transformtion should be identity in EventProducerPushDestination

---

akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

Refs https://github.com/akka/akka-projection/issues/784

test: Harden test of RecoveryStrategy.skip

---

akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java

* awaitAssert, trying to make it more simular to R2dbcProjectionSpec and JdbcProjectionSpec
Refs https://github.com/akka/akka-projection/issues/465

test: Harden JdbcProjectionTest atLeastOnceShouldRestartFromPreviousOffset

---

akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/replication/EdgeReplicationMultiIntegrationSpec.scala
akka-projection-grpc-tests/src/test/java/akka/projection/grpc/replication/javdsl/ReplicationCompileTest.java
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/replication/scaladsl/ProducerApiSample.scala
akka-projection-grpc/src/main/mima-filters/1.5.1-M1.backwards.excludes/edge-initiated-multiple-entities.excludes
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/Transformation.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventPusher.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventPusherConsumerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/internal/ReplicationImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/javadsl/Replication.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/scaladsl/Replication.scala

I don't have test coverage but I think this also covers the combination of regular push projections and a replicated entity (needed for the Drone sample)

feat: Accept/push-publish multiple RES types from edge

---

.scala-steward.conf
project/Dependencies.scala
samples/grpc/iot-service-scala/build.sbt
samples/grpc/local-drone-control-java/pom.xml
samples/grpc/local-drone-control-scala/build.sbt
samples/grpc/restaurant-drone-deliveries-service-java/pom.xml
samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt
samples/grpc/shopping-analytics-service-java/pom.xml
samples/grpc/shopping-analytics-service-scala/build.sbt
samples/grpc/shopping-cart-service-java/pom.xml
samples/grpc/shopping-cart-service-scala/build.sbt
samples/replicated/shopping-cart-service-java/pom.xml
samples/replicated/shopping-cart-service-scala/build.sbt

Only in tests and samples. I don't know if there was a reason for not using the same version as in Akka https://github.com/akka/akka-projection/pull/828 ?

bump: logback 1.2.13

---

docs/release-train-issue-template.md
samples/grpc/iot-service-scala/build.sbt
samples/grpc/local-drone-control-java/pom.xml
samples/grpc/local-drone-control-java/src/main/java/charging/ChargingStation.java
samples/grpc/local-drone-control-scala/build.sbt
samples/grpc/local-drone-control-scala/src/main/scala/charging/ChargingStation.scala
samples/grpc/restaurant-drone-deliveries-service-java/pom.xml
samples/grpc/restaurant-drone-deliveries-service-java/src/main/java/charging/ChargingStation.java
samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt
samples/grpc/restaurant-drone-deliveries-service-scala/src/main/scala/charging/ChargingStation.scala
samples/grpc/shopping-analytics-service-java/pom.xml
samples/grpc/shopping-analytics-service-scala/build.sbt
samples/grpc/shopping-cart-service-java/pom.xml
samples/grpc/shopping-cart-service-scala/build.sbt
samples/replicated/shopping-cart-service-java/pom.xml
samples/replicated/shopping-cart-service-scala/build.sbt

We need to bump this before making the release, otherwise the sample zip files will contain the old version.

sample: Akka Projections 1.5.1 in samples

---

.github/workflows/release.yml

* useful when publishing snapshot from non main branch

build: release snapshot via workflow dispatch

---

akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/consumer/scaladsl/EventTimestampQuerySpec.scala

* failed with -47 was not greater than or equal to 0
* db time might be different from local time

test: Harden EventTimestampQuerySpec

---

akka-projection-grpc-integration/src/test/resources/db/default-init.sql
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/TestDbLifecycle.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/ControlledReplicationIntegrationSpec.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/EdgeReplicationIntegrationSpec.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/EdgeReplicationJavaDSLIntegrationSpec.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/EdgeReplicationMultiIntegrationSpec.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/IndirectReplicationIntegrationSpec.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/PushReplicationIntegrationSpec.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/ReplicationJavaDSLIntegrationSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventProducerServiceImpl.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala

I'll have to test this more, and think about if it is the right solution. It works for the reported problematic scenario.
* EventOriginFilter is only used for ReplicatedEventSourcing
* It was applied after the FilterStage and therefore also filtered events from replay requests. That works if the replica can instead receive the event from the origin replica, but if combined with dynamic consumer filter the original replica may not emit anything due to the consumer filter on that replica.
* Solution is to use the EventOriginFilter inside the FilterStage instead, so that is not used for replay requests.

fix: replicatedEventOriginFilter should not filter replayed events

---

akka-projection-core/src/main/scala/akka/projection/internal/CanTriggerReplay.scala
akka-projection-core/src/main/scala/akka/projection/internal/JavaToScalaSourceProviderAdapter.scala
akka-projection-core/src/main/scala/akka/projection/internal/ScalaToJavaSourceProviderAdapter.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
akka-projection-grpc-integration/src/test/scala/akka/projection/grpc/replication/ControlledReplicationIntegrationSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala
akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala
akka-projection-grpc/src/main/mima-filters/1.5.2.backwards.excludes/res-replay-filter.excludes
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/ConsumerFilter.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/javadsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerFilterRegistry.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala

* filters are not used in replay requests, because the change of consumer
filter is typically what triggers a replay request (missing preceding events)
* but that means that a replica may receive unexpected events, so
apply the filters after the sequence number that triggered the replay

fix: unexpected events when controlling replication with consumer filter

---

build.sbt

Avoid `akka-projection-kafka` to include `akka-projection-testkit` via non-test scoped builds.

fix: kafka to depend on testkit via Test scope

---

.github/workflows/integration-tests-r2dbc.yml
docker-files/docker-compose-sqlserver.yml

Latest version currently failing to start.
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "/opt/mssql-tools/bin/sqlcmd": stat /opt/mssql-tools/bin/sqlcmd: no such file or directory: unknown
```
Looks like this path `/opt/mssql-tools/bin/sqlcmd` is now `/opt/mssql-tools18/bin/sqlcmd`. But updating that then fails with:
```
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : SSL Provider: [error:0A000086:SSL routines::certificate verify failed:self-signed certificate].
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to localhost. Server is not found or not …
```

ci: pin sqlserver to the previous version

---

samples/replicated/shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCart.java

I discovered that the sample project from the [Akka DC docs](https://doc.akka.io/docs/akka-distributed-cluster/current/guide/4-deploying.html) was throwing an error, when I run the following command from the README:
```
grpcurl -d '{"cartId":"cart1"}' -plaintext 127.0.0.1:8101 shoppingcart.ShoppingCartService.MarkCustomerVip
```
The java implementation was missing an event handler for the `CustomerMarkedVip` event, so I added it.
The scala implementation is working correct.

Fix Distributed Cluster Example Project 

---

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala
akka-projection-grpc/src/main/mima-filters/1.5.4.backwards.excludes/internal-proto-offset.excludes
akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtobufProtocolConversions.scala

Depends on https://github.com/akka/akka/pull/32479 to be published first.

feat: support timestamp offset by slice for grpc projections

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

Refining the selected timestamp offset after projection scaling. Before if it saw there were multiple projection keys, it would use the earliest of the latest by slice. But if just one of the slices has not had recent activity and is far behind, we go back to that timestamp offset on each projection scaling or restart, replaying many events.
Update this to use the earliest of the latest grouped by projection key (by slice range), to still handle the case where a previous projection instance may have been falling behind. Also recheck that there are multiple projection keys, within the latest offsets by slice.
Tested and this improves things a lot. But there can still be cases where a particular slice is far behind, and with projection scaling, happened to be processed by a projection …

fix: refine start offset after downscaling

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

To trigger deletion of old timestamp offsets, the current condition is that both the number of entries (persistence ids) is over the limit (10000 by default) and the oldest to latest offset window is longer than the time window. Wonder if that was intended to instead be if it's either over the limit or outside the window to trigger deletion?

fix: condition for deleting old timestamp offsets

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConsumerFilterRegistry.scala

Noticed this occasionally:
```
Caused by: akka.grpc.GrpcServiceException: NOT_FOUND: Stream id [customer] is not available for consumption
at akka.grpc.GrpcServiceException$.apply(GrpcServiceException.scala:40)
at akka.grpc.internal.RequestBuilderImpl$.lift(RequestBuilderImpl.scala:481)
at akka.grpc.internal.RequestBuilderImpl$$anonfun$richErrorStream$1.applyOrElse(RequestBuilderImpl.scala:473)
at akka.grpc.internal.RequestBuilderImpl$$anonfun$richErrorStream$1.applyOrElse(RequestBuilderImpl.scala:472)
at akka.stream.impl.fusing.RecoverWith$$anon$43.akka$stream$impl$fusing$RecoverWith$$anon$$onFailure(Ops.scala:2156)
at akka.stream.impl.fusing.RecoverWith$$anon$43.onUpstreamFailure(Ops.scala:2151)
... 21 more
09:00:06.737 ERROR akka.actor.typed.Behavior$ - Supervisor StopSupervisor saw …
```

fix: ConsumerFilterRegistry unique actor name

---

akka-projection-jdbc-integration/src/test/scala/akka/projection/jdbc/JdbcContainerOffsetStoreSpec.scala
akka-projection-slick-integration/src/test/scala/akka/projection/slick/SlickContainerOffsetStoreSpec.scala
container-license-acceptance.txt

Sql server in old image failing to start because of something unclear (triggered by time, no related changes)

build: Bump Akka Projection JDBC it test MS Sql Server image

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/resources/reference.conf
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/OffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/PostgresOffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

Backport of https://github.com/akka/akka-projection/pull/1218
* improvement for projection scaling
(cherry picked from commit 9c7168fcd2975fcc67d674df969e018945008947)

fix: adopt offsets from other projection keys (backport 1.5)

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/OffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/PostgresOffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/SqlServerOffsetStoreDao.scala

* makes it more safe to evict from memory, but keep more in database
* a step towards lazy loading of offsets, but full lazy loading would require many more changes due to the concurrency model used in the R2dbcOffsetStore
* otherwise it will use timestampOf, which are be more costly for gRPC projections
* it still falls back to timestampOf as last resort

perf: Try to load previous seqNr if missing, in validation

---

project/Dependencies.scala
samples/grpc/iot-service-java/pom.xml
samples/grpc/iot-service-scala/build.sbt
samples/grpc/local-drone-control-java/pom.xml
samples/grpc/local-drone-control-scala/build.sbt
samples/grpc/restaurant-drone-deliveries-service-java/pom.xml
samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt
samples/grpc/shopping-analytics-service-java/pom.xml
samples/grpc/shopping-analytics-service-scala/build.sbt
samples/grpc/shopping-cart-service-java/pom.xml
samples/grpc/shopping-cart-service-scala/build.sbt
samples/replicated/shopping-cart-service-scala/build.sbt

Not strictly needed, but some good improvements in https://github.com/akka/akka-persistence-r2dbc/pull/615 that we want to promote

bump: akka-persistence-r2dbc 1.2.6 (backport 1.5)

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/OffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/PostgresOffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/SqlServerOffsetStoreDao.scala

Backport of https://github.com/akka/akka-projection/pull/1197
* perf: Try to load previous seqNr if missing, in validation
* makes it more safe to evict from memory, but keep more in database
* a step towards lazy loading of offsets, but full lazy loading would require many more changes due to the concurrency model used in the R2dbcOffsetStore
* otherwise it will use timestampOf, which are be more costly for gRPC projections
* it still falls back to timestampOf as last resort
* different sql for SqlServer
(cherry picked from commit e956248d81634c8d6b234bf4a3600e2889ffbd94)

perf: Try to load previous seqNr if missing, in validation (backport 1.5)

---

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ConnectionException.scala

References https://github.com/lightbend/kalix-runtime/issues/2916

chore: Log GrcpReadJournal connection failure details at debug

---

akka-projection-dynamodb/src/main/resources/reference.conf
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/DynamoDBProjectionSettings.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala

References https://github.com/akka/akka-projection/pull/1222#discussion_r1813297496
The offset retrieval query performs a query for each slice in its range (up to 1024 in the case of a single-instance projection, which might be used if the projection is for an entity with an expected-to-be-low rate of events); these queries are performed simultaneously and all in a given invocation must succeed.  The default number of HTTP connections to dynamo is likely to be less than the number of queries, so these queries will be queued (by dynamo) with other persistence operations (in the case where projections are started early in the application's lifecycle, there may likewise be a surge of persistence operations as shards are rebalanced to the application instance), which may have undesirable …

feat (dynamodb): Configurable parallelism in initial offset store query

---

docs/src/main/paradox/management.md

The management API can only be used against running projections. It will fail if tried outside.

docs: note for running projections using management api

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBOffsetStoreStateSpec.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetStoreSpec.scala
akka-projection-dynamodb/src/main/resources/reference.conf
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/DynamoDBProjectionSettings.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala

* don't use evicted state when saving changed timestamp per slice
* evict time window for each slice
* remove keep-number-of-entries and evict-interval

fix: DynamoDB evict offsets per slice

---

build.sbt

I've manually fixed 1.6.2 and 1.6.1

docs: push akka-edge and akka-distributed-cluster to the right directory

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBOffsetStoreStateSpec.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetStoreSpec.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala

Follow up to https://github.com/akka/akka-projection/pull/1247
Less memory usage

chore: Only keep latest per pid in DynamoDbOffsetStore bySliceSorted

---

akka-projection-dynamodb/src/main/resources/reference.conf
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/DynamoDBProjectionSettings.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/OffsetStoreDao.scala

The major fix here is retrying unprocessed batch-write items in the OffsetStoreDao: while the individual writes are atomic, the batch is not and reports partial success as a successful CompletionStage: it's on the caller to check that all items succeeded and retry ones that didn't.

fix: DynamoDB - Avoid dropping sequence number progress

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetStoreSpec.scala
akka-projection-dynamodb/src/main/resources/reference.conf
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/DynamoDBProjectionSettings.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala

* base the validaiton time window for the previous sequence number
on start timestamp and backtracking window
Corresponding to https://github.com/akka/akka-projection/pull/1246

fix: DynamoDB Timestamp validation of previous seqNr

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetProjectionSpec.scala
akka-projection-jdbc-integration/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala

* failing test: "store offset for failing events when using RecoveryStrategy.skip"
* projection might have been stopped before the error occured

test: Harden DynamoDBTimestampOffsetProjectionSpec

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBOffsetStoreStateSpec.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetStoreSpec.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala

If, when recovering a backlog in an at-least-once projection, the range of event timestamps from a slice in a given batch of records to have offsets saved exceeds the offset store's `time-window`, the older events will be immediately evicted; since the inflight records are cleaned based on the state after evicting, this implies that the records for those older events will continue to be considered inflight.
If there are no further events for a persistence ID that was immediately evicted, this means a leak in inflight (if there are enough of these situations, the hard limit of 10k records inflight will get breached) eventually resulting in projection failure.
Note that sequence numbers are saved based on the incoming records, so this eviction will not prevent seen sequence numbers from …

fix: [DynamoDB] Ensure that inflight persistence IDs are not evicted

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetProjectionSpec.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/TestSourceProviderWithInput.scala
akka-projection-dynamodb/src/main/mima-filters/1.6.3.backwards.excludes/offset-store.excludes
akka-projection-dynamodb/src/main/resources/reference.conf
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/DynamoDBProjectionSettings.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBProjectionImpl.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
build.sbt
project/Dependencies.scala

To handle unforeseen cases of rejection it will replay missing events via CurrentEventsByPersistenceIdTypedQuery
Also bumps akka-persistence-dynamodb to 2.0.3, since CurrentEventsByPersistenceIdTypedQuery is implemented in that version.
Refs https://github.com/akka/akka-projection/issues/1276

fix: DynamoDB replay rejected events

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetProjectionSpec.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBProjectionImpl.scala

Just a quick fix to get replays working for javadsl.
Extending the adapters to cover `LoadEventsByPersistenceIdSourceProvider` as well could be better. But adapters are sealed, load events is under event sourced projections, and there would need to be combinations for with or without `CanTriggerReplay`.
So just pull out the underlying provider when adapted for now, which implements `LoadEventsByPersistenceIdSourceProvider`. 
We also don't seem to be set up for testing the javadsl currently, so only confirmed manually. Can follow up with tests.

fix: handle adapted java source providers for replay

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreStateSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/mima-filters/1.6.5.backwards.excludes/r2dbc-offset-store.excludes
akka-projection-r2dbc/src/main/resources/reference.conf
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/OffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/PostgresOffsetStoreDao.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/SqlServerOffsetStoreDao.scala

* evict time window for each slice
* remove keep-number-of-entries and evict-interval
* lazy loading of offsets
* delete detached from time window, separate delete-after config

fix: R2dbcOffsetStore evict and delete per slice

---

akka-projection-dynamodb-integration/src/test/resources/logback-test.xml
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/EventSourcedEndToEndSpec.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/TestConfig.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/TestDbLifecycle.scala

* inspired by corresponding test for r2dbc
* testing all projection types with real source provider
I can bring this back to the r2dbc.EventSourcedEndToEndSpec

test: DynamoDB EventSourcedEndToEndSpec

---

akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

We've been seeing unnecessary rejection (and replay) of events. There can be a large enough gap between events, so that all older offsets for a pid have been deleted, while the previous timestamp is after the start timestamp (minus the backtracking window, the current accept before time). Then any later events for that pid will be rejected.
Deletion is now per slice, offsets are lazy loaded when not in-memory, and the offset table should have at least the latest offset for each slice. So we can instead accept seq numbers if the previous offset could have been deleted (it's before the delete-until timestamp for its slice).
At first, because of other tests failing when a slice was untracked, I had it fallback to the previous accept-before timestamp (start minus backtracking). But given that …

fix(r2dbc): avoid unnecessary rejection given deleted offsets

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/EventSourcedEndToEndSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/StartFromSnapshotEndToEndSpec.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/TestConfig.scala

Extend the r2dbc EventSourcedEndToEndSpec to other projection types, following #1282 for DynamoDB.

test: extend R2DBC EventSourcedEndToEndSpec

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetStoreSpec.scala
akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/TestClock.scala
akka-projection-dynamodb/src/main/mima-filters/1.6.5.backwards.excludes/dynamodb-offset-store.excludes
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/OffsetStoreDao.scala

Similar changes as #1293 for DynamoDB, but using TTL expiry.
While for R2DBC, we're managing the offset deletion, and basing this on the event timestamps, for DynamoDB it's just a simple TTL expiry set when the offset is written. So we use an accept before time that's just based on now minus the expiry.
When looking at this, noticed the expiry set on the separate latest-by-slice offsets. To keep things safer, have removed this expiry, so we always keep this for restarting a projection, while the per-pid offsets will be expired.

fix(dynamodb): avoid unnecessary rejection given expired offsets

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetStoreSpec.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

* concurrency issue in R2dbcOffsetStore when saving offsets in case of concurrent modifications
* map vs flatMap
* DynamoDB was correct
* added some more logging

fix(r2dbc): Leak of in-flight offsets

---

project/Dependencies.scala

Also bump to align on AWS SDK versions. Make this simpler in the future: don't manage the DynamoDB SDK version separately here in projections, and always use the transient dependency from akka-persistence-dynamodb instead.

bump: akka-persistence-dynamodb 2.0.5

---

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala
akka-projection-grpc/src/main/scala/akka/projection/grpc/replication/internal/ReplicationImpl.scala

* it should be replicaId and not persistenceId

fix: Wrong VersionVector when migrated from non-replicated

---

akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/Requests.scala

When we bump to next Akka core version that includes https://github.com/akka/akka/pull/32607

chore: Use public api for exp backoff delay

---

akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala
akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
akka-projection-core/src/main/scala/akka/projection/internal/ObservableHandler.scala
akka-projection-core/src/main/scala/akka/projection/internal/ProjectionContextImpl.scala
akka-projection-core/src/main/scala/akka/projection/scaladsl/Handler.scala
akka-projection-dynamodb/src/main/mima-filters/1.6.8.backwards.excludes/adapted-handlers.excludes
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBProjectionImpl.scala
akka-projection-r2dbc/src/main/mima-filters/1.6.8.backwards.excludes/adapted-handlers.excludes
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala

Projection telemetry has been on the outermost handler. For R2DBC and DynamoDB this means that it sees all envelope sources (from pubsub, query, and backtracking), including envelopes that will be deduplicated and not actually processed. When metrics like consumer lag are aggregated across all of these, and with backtracking up to 1 minute behind on average it skews the metric creating confusion. While metrics can be separated across envelope sources, there's no way to know which are actually being processed or deduplicated.
Fix this by only calling telemetry (and status observer) for actual processing of envelopes. Because of the way the telemetry SPI is set up (no started hook, creation of the telemetry object indicates projection start), it's not possible to simply move the telemetry …

fix: handler observability for r2dbc and dynamodb

---

akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
akka-projection-r2dbc/src/main/resources/reference.conf
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala

* use case is when migrating (from jdbc) and there are no previously stored offsets and the projections start from a specific time

feat: Configuration to accept when previous is old

---

akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBProjectionImpl.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala

* since those may be out of sync more frequently and the replay will increase the load on the system/db
* note that this also applies to grpc projections

fix: Don't trigger replay from pub-sub events

---

akka-projection-dynamodb-integration/src/test/scala/akka/projection/dynamodb/DynamoDBTimestampOffsetProjectionSpec.scala
akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBProjectionImpl.scala
akka-projection-r2dbc-integration/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala

After replay we were returning None, filtering out the rejected envelope, so the offset was never stored.
Test was already reproducing it, but masked by checking the latest offset was correct, which happened to be for a pid that had processed another envelope after its replay. Adjust the test to check latest offset for all slices.
Update to only replay up to the currently rejected envelope, and then process this envelope through the flow as usual.

fix: ensure offset stored after replay for flow projections

---

akka-projection-core-test/src/test/scala/akka/projection/internal/metrics/BacklogStatusTelemetrySpec.scala
akka-projection-core-test/src/test/scala/akka/projection/internal/metrics/tools/InMemTelemetry.scala
akka-projection-core-test/src/test/scala/akka/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala
akka-projection-core/src/main/scala/akka/projection/internal/BacklogStatus.scala
akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
akka-projection-core/src/main/scala/akka/projection/internal/JavaToScalaSourceProviderAdapter.scala
akka-projection-core/src/main/scala/akka/projection/internal/ScalaToJavaSourceProviderAdapter.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala
akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala

Add backlog status checks, based on the latest event timestamp query, and telemetry SPI extension for reporting these.
Depends on:
- https://github.com/akka/akka/pull/32700
Aligned with:
- https://github.com/akka/akka-persistence-r2dbc/pull/667
- https://github.com/akka/akka-projection/pull/1334

feat: add backlog status telemetry
