akka/akka-projection

version.sbt
=> Remove version.sbt (dynver setup)

akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/ProjectionTestRunner.scala, build.sbt, project/Dependencies.scala
Super minimal Projection API to start with. 
I'm explicitly not adding any Scaladoc or considering a Java variant. The goal is to let it evolve as we explore some other concrete implementations.
=> Projection base trait

.travis.yml
=> Re-add Travis settings for publishing from master (snapshot)'

.travis.yml
=> Ensure that Travis fetch full history

akka-projection-core/src/main/scala/akka/projection/Projection.scala
Elaboration of some of the terms of projections.  Inspired from this comment: https://github.com/akka/akka-projection/pull/45#discussion_r408380439
=> Elaborate terms in Projection

.travis.yml, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/ProjectionTestRunner.scala, build.sbt, docs/src/main/paradox/.htaccess, docs/src/main/paradox/_template/projectSpecificFooter.st, docs/src/main/paradox/assets/js/warnOldVersion.js, docs/src/main/paradox/index.md, docs/src/main/paradox/overview.md, project/Common.scala, project/CopyrightHeader.scala, project/Dependencies.scala, project/plugins.sbt, project/project-info.conf
=> Add documentation creation

akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionId.scala, akka-projection-slick/src/main/resources/reference.conf, akka-projection-slick/src/main/scala/akka/projection/slick/OffsetStore.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/resources/logback-test.xml, akka-projection-slick/src/test/scala/akka/projection/slick/OffsetStoreSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/ProjectionTestKit.scala, akka-projection-testkit/src/test/scala/akka/projection/testkit/ProjectionTestKitSpec.scala, build.sbt, project/Dependencies.scala
Draft PR for Slick Projections
Still need some clean-up, API massage and support for at-least-once
=> Slick Projections - transactional only

.travis.yml
Same as we have in other projects
=> only build certain branches in Travis

project/Common.scala
=> show test output immediatelly and incrementally

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
=> Cassandra at-most-once projection, #21

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/SourceProvider.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/SourceProvider.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
This is in preparation for adding source providers for akka-persistence-query.
=> Introduce SourceProvider

akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
After reading the [Slick documentation of transactions](https://scala-slick.org/doc/3.3.1/dbio.html#transactions) this is the way I think they should be defined.
=> correction of Slick transactions

akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/EventEnvelope.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala, build.sbt, project/Dependencies.scala
=> SourceProviders for Akka Persistence Query

akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionId.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, project/Dependencies.scala
=> ProjectionTestkit for Java DSL

akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/resources/logback-test.xml, akka-projection-slick/src/test/scala/akka/projection/slick/OffsetStoreSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
=> EventHandler trait - Slick

akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/ContainerSessionProvider.scala
* at least until we see that there is a problem
* default is 3 seconds, with 100 ms interval
=> use patience from ScalaTestWithActorTestKit

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/HandlerAdapter.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/Handler.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Handler.scala
* defined in core because it's not specific to Cassandra
References #43
Draft because on top of other PR, but ready for review.
=> Handler trait in Cassandra Projection, #43

project/Dependencies.scala
=> update to Akka 2.6.5

build.sbt, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/eventsourced.md, docs/src/main/paradox/index.md, docs/src/main/paradox/kafka.md, docs/src/main/paradox/overview.md, docs/src/main/paradox/slick.md, docs/src/main/paradox/use-cases.md, project/Dependencies.scala, project/project-info.conf
=> Documentation structure and dependency sections, #79

akka-projection-cassandra/src/main/resources/reference.conf, docs/src/main/paradox/cassandra.md, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/java/jdocs/eventsourced/ShoppingCart.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala
=> reference docs for CassandraProjection

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/resources/logback-test.xml, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/resources/reference.conf, akka-projection-core/src/main/scala/akka/projection/HandlerRecovery.scala, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionSettings.scala, akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSpecBase.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, examples/src/test/scala/akka/projection/examples/KafkaToSlickIntegrationSpec.scala
=> Backoff restarts for failed sources

akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
=> cleanup of CassandraProjectionSpect afterAll

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/resources/reference.conf, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionSettings.scala, akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/resources/logback-test.xml, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala
For merging rgc/restarted-source again into master, #121 was merged on that branch.
=> RunningProjection and isolated internal state (take 2)

docs/src/main/paradox/index.md, docs/src/main/paradox/jpa.md, docs/src/main/paradox/slick.md, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
=> reference docs for SlickProjection

akka-projection-core/src/main/scala/akka/projection/javadsl/Handler.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Handler.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, build.sbt, docs/src/main/paradox/cassandra.md, examples/src/test/scala/akka/projection/cassandra/scaladsl/WordCountDocExampleSpec.scala, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala, project/Dependencies.scala
=> docs for stateful handler

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, examples/src/test/scala/docs/eventsourced/ShoppingCart.scala
* removed unused imports
* use cartId in rejected message
* removed unused parameters
=> Minor warning clean-ups

akka-projection-kafka/src/test/resources/application.conf, akka-projection-kafka/src/test/resources/logback-test.xml, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSpecBase.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala
Hopefully this also resolves #109.  I'll trigger the travis build a few more times to make sure.
=> Add db failure Kafka integration test case

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/HandlerAdapter.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/Handler.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Handler.scala, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, examples/src/test/scala/akka/projection/cassandra/scaladsl/WordCountDocExampleSpec.scala
* will be needed for the functional StatefulHandler, and for integration with actors
=> start/stop lifecycle of Handler

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
=> Expose createOffsetTableIfNotExists for testing purposes

akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala
* issue https://github.com/akka/alpakka-kafka/issues/1115 in Alpakka Kafka that the MetaDataClient creates the actor with system.actorOf, which doesn't work with a Typed ActorSystem
* and stop the ConsumerActor
=> create Kafka ConsumerActor with systemActorOf

akka-projection-core/src/main/scala/akka/projection/javadsl/StatefulHandler.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/StatefulHandler.scala, docs/src/main/paradox/cassandra.md, examples/src/test/java/jdocs/cassandra/WordCountDocExample.java, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala
On top of https://github.com/akka/akka-projection/pull/126
TODO:
=> add functional style StatefulHandler

docs/src/main/paradox/index.md, docs/src/main/paradox/kafka.md, docs/src/main/paradox/projection-settings.md, docs/src/main/paradox/running.md, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/java/jdocs/eventsourced/ShoppingCart.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/eventsourced/ShoppingCart.scala
=> Documentation on running a Projection (Scala/Java)

docs/src/main/paradox/kafka.md, examples/src/test/scala/docs/kafka/KafkaDocExample.scala
On top of #133 
References #79
=> doc how to send to Kafka from Projection

docs/src/main/paradox/running.md
Apply suggestion @seglo did in #129.
The typo on `ShardedDaemonProcess` was already fixed.
=> Late code review suggestions from #129

akka-projection-core/src/main/scala/akka/projection/javadsl/Handler.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/StatefulHandler.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Handler.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/StatefulHandler.scala, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/slick.md, examples/src/test/scala/akka/projection/cassandra/scaladsl/WordCountDocExampleSpec.scala
=> warn about sharing Handler instance

docs/release-train-issue-template.md
root project will not be published
=> fix central link

.travis.yml, project/AkkaSnapshotRepository.scala, project/Dependencies.scala
Temporarily build the test with Akka snapshots to workaround classpath logger issue
References #106
=> Build tests with Akka snaspshot

examples/src/test/scala/akka/projection/cassandra/scaladsl/WordCountDocExampleSpec.scala, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala
=> fix typo: illstrate -> illustrate

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/resources/reference.conf, akka-projection-core/src/main/scala/akka/projection/ProjectionSettings.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/scala/akka/projection/cassandra/scaladsl/WordCountDocExampleSpec.scala, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/kafka/KafkaDocExample.scala, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
Implements #59 to extract atLeastOnce parameters to configuration.
Second try at this implementation (first was #168).  New implementation driven by @patriknw's comments https://github.com/akka/akka-projection/pull/168#discussion_r426386523
=> At Least Once configuration

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraOffsetStoreSpec.scala, docs/src/main/paradox/cassandra.md
=> Cassandra: split projection id field into name and key

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionSettings.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala, akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/KafkaSourceProvider.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/java/jdocs/eventsourced/EventSourcedDocExample.java, examples/src/test/java/jdocs/eventsourced/ShoppingCart.java, examples/src/test/java/jdocs/testkit/TestKitDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/eventsourced/ShoppingCart.scala, examples/src/test/scala/docs/kafka/KafkaDocExample.scala
References #149
Build on top of #162, but ready for review. 
Will remove draft once #162 is merged.
=> Prefer typed ActorSystem to ClassicActorSystemProvider

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/HandlerAdapter.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/resources/reference.conf, akka-projection-core/src/main/scala/akka/projection/ProjectionSettings.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala, akka-projection-core/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/slick.md, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
* group envelopes before the handler
* for example batch updates in the handler
* GroupedHandler with Seq[Envelope]
TODO:
Refs https://github.com/akka/akka-projection/issues/146
=> Support of grouped envelopes

akka-projection-cassandra/src/main/resources/reference.conf, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraSettings.scala, akka-projection-slick/src/main/resources/reference.conf, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/slick.md
* execution profile akka-projection-cassandra-profile,
with consistency QUORUM
* improved configuration documentation
* same as in Akka Persistence Cassandra
References #111
=> Cassandra execution profile, #111

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/HandlerAdapter.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjection.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/OffsetStrategy.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/Projections.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Projections.scala, akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/resources/logback-test.xml, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, docs/src/main/paradox/slick.md, examples/src/test/scala/docs/kafka/KafkaDocExample.scala, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
WIP, still lots of clean-up and it's missing impl for exactly-once grouped and mergeable offset.
=> Introducing generic InternalProjectionState

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Projections.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala
Remove the cast from projection traits and leave it to the impl classes. 
As discussed in #215
=> Move offset strategy cast to impl classes

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerLifecycleAdapter.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/Projections.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/Projections.scala, akka-projection-jdbc/src/main/resources/reference.conf, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala, akka-projection-jdbc/src/test/resources/logback-test.xml, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickSettings.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickOffsetStoreSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, build.sbt, examples/src/test/java/jdocs/jpa/HibernateSessionProvider.java, examples/src/test/java/jdocs/jpa/JdbcProjectionWithHibernateDocExample.java, examples/src/test/resources/application.conf, examples/src/test/resources/persistence.xml, project/Dependencies.scala
=> JDBC Support

akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSpecBase.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, docs/src/main/paradox/cassandra.md, examples/src/test/java/jdocs/cassandra/WordCountDocExample.java, examples/src/test/java/jdocs/cassandra/WordCountDocExampleTest.java, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala, examples/src/test/scala/docs/cassandra/WordCountDocExampleSpec.scala
* completed all WordCountDocExample.java
* also with a test
References #150
=> doc snippets for stateful handler in Java, #150

docs/src/main/paradox/running.md, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala
=> Document running alternatives, #152

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, docs/src/main/paradox/testing.md, examples/src/test/java/jdocs/testkit/TestKitDocExample.java
=> Remove withSettings method

akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala
While troubleshooting #200 I noticed that for the default `ProjectionTestKit.run` method overload we dilate a `FiniteDuration` that is already dilated internally by the Akka typed testkit (`TestKitSettings.SingleExpectDefaultTimeout`), resulting in an exponentially larger default timeout.
This fix may cause some tests to fail that required this longer timeout, but we can resolve that with increasing the default dilation factor in the same way I'm doing in #200.
=> Fix double default dilation

akka-projection-core/src/main/resources/reference.conf, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/error.md, docs/src/main/paradox/index.md, docs/src/main/paradox/slick.md, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala
=> document error handling, #189

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionContext.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/OffsetStrategy.scala, akka-projection-core/src/main/scala/akka/projection/internal/ProjectionContextImpl.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
(built on top of #215)
References #217
=> Replace tuple with a custom type

examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala
As suggested here:
https://github.com/akka/akka-projection/pull/235#discussion_r439469437
Unfortunately, the javadsl is impacted a small bug that will be fixed in https://github.com/akka/akka/pull/29235
=> use new sharded daemon simplified API

akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/SourceProvider.scala, akka-projection-core/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala, project/AkkaDisciplinePlugin.scala, project/Common.scala
Basically picked the AkkaDisciplinePlugin with a few minor changes.
=> Stricter compiler settings and silencer plugin

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerAdapter.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/ActorHandler.scala, docs/src/main/paradox/actor.md, examples/src/test/java/jdocs/cassandra/WordCountDocExample.java, examples/src/test/java/jdocs/cassandra/WordCountDocExampleTest.java, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala
Java examples corresponding to Scala examples that were added previously.
References #144
=> Java doc sample for actor handler, #144

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/javadsl/CassandraProjection.scala, akka-projection-cassandra/src/main/scala/akka/projection/cassandra/scaladsl/CassandraProjection.scala, akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/OffsetStrategy.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/javadsl/KafkaSourceProvider.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, docs/src/main/paradox/cassandra.md, examples/src/test/java/jdocs/cassandra/CassandraProjectionDocExample.java, examples/src/test/java/jdocs/cassandra/WordCountDocExampleTest.java, examples/src/test/java/jdocs/jpa/JdbcProjectionWithHibernateDocExample.java, examples/src/test/java/jdocs/kafka/KafkaDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/cassandra/WordCountDocExampleSpec.scala, examples/src/test/scala/docs/kafka/KafkaDocExample.scala, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
=> Make projections take a handler factory instead of a handler instance, #202

akka-projection-kafka/src/main/scala/akka/projection/kafka/javadsl/KafkaSourceProvider.scala
fatal warning in master (due to merge)
=> fix fatal warning

akka-projection-jdbc/src/main/resources/reference.conf, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, akka-projection-slick/src/main/resources/reference.conf, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala
=> [JDBC] Support for multi-offsets

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-core/src/main/scala/akka/projection/Projection.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionBehavior.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionId.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerAdapter.scala, akka-projection-core/src/main/scala/akka/projection/internal/HandlerRecoveryImpl.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/OffsetSerialization.scala, akka-projection-core/src/main/scala/akka/projection/internal/SourceProviderAdapter.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/ProjectionManagement.scala, akka-projection-core/src/test/java/akka/projection/ProjectionBehaviorCompileTest.java, akka-projection-core/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-core/src/test/scala/akka/projection/internal/OffsetSerializationSpec.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickProjectionImpl.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, build.sbt, examples/src/test/java/jdocs/testkit/TestKitDocExample.java, examples/src/test/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/kafka/KafkaDocExample.scala, examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala, project/Common.scala, project/Dependencies.scala
=> Cross compile to Scala 2.12 and 2.13

akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/SourceProviderAdapter.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/SourceProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, examples/src/test/java/jdocs/cassandra/WordCountDocExample.java, examples/src/test/java/jdocs/kafka/KafkaDocExample.java, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala, examples/src/test/scala/docs/kafka/KafkaDocExample.scala
This is complements the changes in #250.
=> SourceProvider with fixed mat to NotUsed

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
=> [JDBC] Support for flow handler

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
Draft because on top of 255.
Ready for review otherwise.
References #23
=> [JDBC] Support for offset management

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
Draft because on top of #261.
Ready for review otherwise.
References #23
=> [JDBC] support for at-least-once

akka-projection-core/src/main/scala/akka/projection/OffsetVerification.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
=> Run post verify offsets after database operation is performed

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSessionUtil.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala, project/Dependencies.scala
=> JdbcOffsetStore: Postgres and MySQL support

akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraOffsetStore.scala, akka-projection-core/src/main/scala/akka/projection/internal/OffsetSerialization.scala, akka-projection-core/src/main/scala/akka/projection/internal/ProjectionSerializer.scala, akka-projection-core/src/test/scala/akka/projection/internal/OffsetSerializationSpec.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala, akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickOffsetStoreSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/slick.md
* the Spanner offset will be supported in this way, serializer to be added to the Spanner plugin
References #41
=> support other offset types via Akka serialization, #41

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcProjection.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
This was trivial
References #23
=> support Future based Handler in JdbcProjction, #23

.gitignore, .travis.yml, akka-projection-jdbc/src/main/resources/reference.conf, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, container-license-acceptance.txt, docs/src/main/paradox/jdbc.md, project/Dependencies.scala
Draft because on top of #273.
Ready for review otherwise.
References #23
=> Added support for MS SQL Server

akka-projection-core/src/main/scala/akka/projection/HandlerRecoveryStrategy.scala, akka-projection-core/src/main/scala/akka/projection/internal/Telemetry.scala
* and some more minor cleanup there
=> fix compilation error in Telemetry

project/AkkaSnapshotRepository.scala
=> Add snapshot resolvers in travis when using alpakka-kafka snapshots

akka-projection-core/src/test/scala/akka/projection/internal/metrics/LifecycleMetricSpec.scala
=> Harden Lifecycle Metrics Spec

.travis.yml
I've had a couple of failures in Travis because of Jabba downloads.
This is a copy/paste from https://github.com/lagom/lagom/pull/2908
=> Cache Jabba. Add retries on download

akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java
=> Fix flaky testkit test

akka-projection-cassandra/src/test/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/test/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/SourceProviderAdapter.scala, akka-projection-core/src/main/scala/akka/projection/internal/Telemetry.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/SourceProvider.scala, akka-projection-core/src/test/scala/akka/projection/internal/metrics/WaitTimeMetricSpec.scala, akka-projection-core/src/test/scala/akka/projection/internal/metrics/tools/InMemTelemetry.scala, akka-projection-core/src/test/scala/akka/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, examples/src/test/java/jdocs/cassandra/WordCountDocExample.java, examples/src/test/java/jdocs/kafka/KafkaDocExample.java, examples/src/test/scala/docs/cassandra/WordCountDocExample.scala, examples/src/test/scala/docs/kafka/KafkaDocExample.scala
References #232
@ignasi35 I'm not sure if you had anything else in mind for this.  I'll leave the calling side impl to you.
=> Extract envelope creation time source provider

.travis.yml, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala, project/AkkaDisciplinePlugin.scala, project/Common.scala, project/Dependencies.scala
=> Enable Scala 2.13 crossbuild in Travis

akka-projection-core/src/test/scala/akka/projection/internal/metrics/WaitTimeMetricSpec.scala
=> Cleanup a copy-paste leftover

docs/src/main/paradox/jdbc.md
=> Product name reviews

akka-projection-jdbc/src/main/resources/reference.conf, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcOffsetStore.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, docs/src/main/paradox/jdbc.md, project/Dependencies.scala
Draft because on top of ~#280~ #306.
References #23
=> Oracle support

akka-projection-core/src/main/scala/akka/projection/internal/Telemetry.scala, akka-projection-core/src/test/scala/akka/projection/internal/TelemetryProviderSpec.scala, akka-projection-core/src/test/scala/akka/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala
=> Support multiple telemetry implementations

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/JdbcHandlerLifecycle.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcHandlerAdapter.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcHandler.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/scaladsl/JdbcHandler.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
=> JdbcHandlerLifecycle for blocking start/stop support

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcSettings.scala
When merging #323, I wrongly resolved a conflict on the error message. This fix it.
=> Error message shows wrongly configured value

akka-projection-kafka/src/test/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala
=> Temporarily disabling Kafka Specs

akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala, akka-projection-core/src/main/scala/akka/projection/internal/InternalProjectionState.scala, akka-projection-core/src/main/scala/akka/projection/internal/NoopStatusObserver.scala, akka-projection-core/src/test/scala/akka/projection/TestStatusObserver.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcProjectionSpec.scala
=> Observer/telemetry: progress reports iff offset has been committed

docs/src/main/paradox/slick.md
=> Adds note wrt Slick purpose

akka-projection-core/src/main/scala/akka/projection/StatusObserver.scala
=> Document limitations for  in statusObserver

docs/src/main/paradox/getting-started/running.md, examples/src/test/scala/docs/guide/EventGeneratorApp.scala, examples/src/test/scala/docs/guide/ShoppingCartApp.scala
=> Prefer numerical over geographical tags

docs/src/main/paradox/cassandra.md, docs/src/main/paradox/jdbc.md, docs/src/main/paradox/slick.md
=> A note on idempotence

docs/src/main/paradox/cassandra.md, docs/src/main/paradox/eventsourced.md, docs/src/main/paradox/jdbc.md, docs/src/main/paradox/kafka.md, docs/src/main/paradox/slick.md, project/plugins.sbt
=> MergeableOffset docs

examples/src/test/scala/docs/jdbc/JdbcProjectionDocExample.scala
While reviewing the code for #363 I noticed some dead code in the samples.
=> Remove unused Executioncontexts

docs/src/main/paradox/kafka.md
References https://github.com/akka/akka-projection/pull/362#discussion_r458683915
=> Add missing bit on the class name

docs/src/main/paradox/kafka.md, examples/src/test/java/jdocs/kafka/KafkaDocExample.java, examples/src/test/scala/docs/kafka/KafkaDocExample.scala
=> Document how to Alpakka Kafka Producer flow

akka-projection-core/src/main/scala/akka/projection/internal/Telemetry.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/TestProjection.scala
=> Use private[projection] instead of private[akka]

akka-projection-kafka/src/it/scala/akka/projection/kafka/KafkaSourceProviderSpec.scala, akka-projection-kafka/src/it/scala/akka/projection/kafka/integration/KafkaToSlickIntegrationSpec.scala, akka-projection-kafka/src/main/scala/akka/projection/kafka/internal/KafkaSourceProviderImpl.scala
=> Kafka: Bugfix: Resume from last processed offset plus one

akka-projection-core-test/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/TestProjection.scala, docs/src/main/paradox/testing.md, examples/src/test/java/jdocs/testkit/TestKitDocExample.java, examples/src/test/scala/docs/testkit/TestKitDocExample.scala
_based on #378, review that first_
Fixes #198 
See inline notes.
=> TestProjection and TestSourceProvider for Testkit

akka-projection-cassandra/src/it/java/akka/projection/cassandra/CassandraProjectionTest.java, akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-jdbc/src/test/java/akka/projection/jdbc/JdbcProjectionTest.java, akka-projection-kafka/src/it/scala/akka/projection/kafka/KafkaSpecBase.scala, akka-projection-kafka/src/test/scala/akka/projection/kafka/internal/KafkaSourceProviderImplSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/javadsl/ProjectionTestKit.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala, akka-projection-testkit/src/test/java/akka/projection/testkit/javadsl/ProjectionTestKitTest.java, akka-projection-testkit/src/test/resources/logback-test.xml, akka-projection-testkit/src/test/scala/akka/projection/testkit/scaladsl/ProjectionTestKitSpec.scala, docs/src/main/paradox/getting-started/testing.md, examples/src/it/java/jdocs/cassandra/WordCountDocExampleTest.java, examples/src/it/scala/docs/cassandra/WordCountDocExampleSpec.scala, examples/src/test/java/jdocs/jdbc/JdbcHibernateTest.java, examples/src/test/java/jdocs/testkit/TestKitDocExample.java, examples/src/test/scala/docs/guide/ShoppingCartAppSpec.scala, examples/src/test/scala/docs/testkit/TestKitDocExample.scala
=> DRY ProjectionTestKit implementation, #220

docs/src/main/paradox/getting-started/projection-handler.md, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/getting-started/testing.md, examples/src/test/scala/docs/guide/ShoppingCartApp.scala, examples/src/test/scala/docs/guide/ShoppingCartAppSpec.scala
=> Re-factor getting started guide example

docs/src/main/paradox/getting-started/error-handling.md, docs/src/main/paradox/getting-started/index.md, docs/src/main/paradox/getting-started/monitoring.md, docs/src/main/paradox/getting-started/offset-management.md, docs/src/main/paradox/getting-started/projection-handler.md, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/getting-started/testing.md, examples/src/test/scala/docs/guide/EventGeneratorApp.scala, examples/src/test/scala/docs/guide/ShoppingCartApp.scala, examples/src/test/scala/docs/guide/ShoppingCartAppSpec.scala
=> Add EventGeneratorApp to getting started guide

docs/src/main/paradox/getting-started/index.md, docs/src/main/paradox/getting-started/running-cluster.md, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/getting-started/source-provider.md, examples/src/test/resources/guide-shopping-cart-cluster-app.conf, examples/src/test/scala/docs/guide/EventGeneratorApp.scala, examples/src/test/scala/docs/guide/ShoppingCartApp.scala
_Based on #396_
Fixes #375 
I'll factor out all the different components of the code from `ShoppingCartApp` in a follow up PR to make it easier for end users to copy and paste snippets with imports, etc.
=> Add running in akka cluster section to getting started guide

docs/src/main/paradox/classic.md, docs/src/main/paradox/index.md, docs/src/main/paradox/overview.md, examples/src/test/java/jdocs/classic/ClassicDocExample.java, examples/src/test/scala/docs/classic/ClassicDocExample.scala
=> doc how to use from Akka classic

docs/src/main/paradox/getting-started/projection-handler.md, docs/src/main/paradox/getting-started/running-cluster.md, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/getting-started/setup-your-app.md, docs/src/main/paradox/getting-started/source-provider.md, examples/src/test/scala/docs/guide/EventGeneratorApp.scala, examples/src/test/scala/docs/guide/ItemPopularityProjectionHandler.scala, examples/src/test/scala/docs/guide/ItemPopularityProjectionRepository.scala, examples/src/test/scala/docs/guide/ShoppingCartApp.scala, examples/src/test/scala/docs/guide/ShoppingCartClusterApp.scala, examples/src/test/scala/docs/guide/ShoppingCartEvents.scala, examples/src/test/scala/docs/guide/ShoppingCartTags.scala
=> Split getting started guide code into separate files

docs/src/main/paradox/error.md, docs/src/main/paradox/running.md, examples/src/it/scala/docs/cassandra/CassandraProjectionDocExample.scala, examples/src/test/scala/docs/eventsourced/ShoppingCart.scala, examples/src/test/scala/docs/guide/ShoppingCartClusterApp.scala
=> Describe how many tags that should be used

akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/EventEnvelope.scala, build.sbt, docs/src/main/paradox/getting-started/projection-handler.md, docs/src/main/paradox/getting-started/running-cluster.md, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/getting-started/setup-your-app.md, docs/src/main/paradox/getting-started/source-provider.md, docs/src/main/paradox/getting-started/testing.md, examples/src/test/java/jdocs/guide/CborSerializable.java, examples/src/test/java/jdocs/guide/EventGeneratorApp.java, examples/src/test/java/jdocs/guide/ItemPopularityProjectionHandler.java, examples/src/test/java/jdocs/guide/ItemPopularityProjectionRepository.java, examples/src/test/java/jdocs/guide/ShoppingCartApp.java, examples/src/test/java/jdocs/guide/ShoppingCartAppTest.java, examples/src/test/java/jdocs/guide/ShoppingCartClusterApp.java, examples/src/test/java/jdocs/guide/ShoppingCartEvents.java, examples/src/test/java/jdocs/guide/ShoppingCartTags.java, examples/src/test/resources/guide-shopping-cart-app.conf, examples/src/test/resources/guide-shopping-cart-cluster-app.conf, examples/src/test/scala/docs/classic/ClassicDocExample.scala, examples/src/test/scala/docs/guide/CborSerializable.scala, examples/src/test/scala/docs/guide/EventGeneratorApp.scala, examples/src/test/scala/docs/guide/ItemPopularityProjectionHandler.scala, examples/src/test/scala/docs/guide/ItemPopularityProjectionRepository.scala, examples/src/test/scala/docs/guide/ShoppingCartApp.scala, examples/src/test/scala/docs/guide/ShoppingCartAppSpec.scala, examples/src/test/scala/docs/guide/ShoppingCartClusterApp.scala, examples/src/test/scala/docs/guide/ShoppingCartTags.scala
=> Getting started guide, Java version

build.sbt
* included dependency to core-tests and also a testkit dependency as full dependencies
References #409
=> fix dependency scopes

build.sbt, project/Dependencies.scala
This fix and clean-ups the dependencies on the test modules.
=> Fix dependencies on test modules

akka-projection-jdbc/src/main/scala/akka/projection/jdbc/javadsl/JdbcProjection.scala
* was by accident Scala function
=> change to Supplier in JdbcProjection.createOffsetTableIfNotExists

akka-projection-jdbc/src/it/resources/db/default-init.sql, akka-projection-jdbc/src/it/resources/db/oracle-init.sql, akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcContainerOffsetStoreSpec.scala, akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-jdbc/src/test/scala/akka/projection/jdbc/JdbcOffsetStoreSpec.scala, examples/src/test/resources/create-table-mssql.sql
References #420 
In this PR:
* JDBC Offset store integration tests setup a custom schema in the DB
* The SQL dialects are adjusted accordingly to properly reference tables within schemas.
=> Schema and table names quoted independently (#420)

akka-projection-core/src/main/scala/akka/projection/MergeableOffset.scala, akka-projection-core/src/main/scala/akka/projection/ProjectionId.scala, akka-projection-core/src/main/scala/akka/projection/internal/ProjectionSettings.scala, akka-projection-core/src/main/scala/akka/projection/javadsl/SourceProvider.scala, akka-projection-core/src/main/scala/akka/projection/scaladsl/SourceProvider.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/Dialect.scala, akka-projection-slick/src/main/scala/akka/projection/slick/SlickProjection.scala
Last round for annotating public APIs with `@ApiMayChange` and internal APIs with `@InternalApi`
References #96
=> Adds ApiMayChange and InternalApi - last round

build.sbt, project/project-info.conf
Now that 1.0.0 is released.
Make it "Akka Projections" in the docs.
=> Change readiness level to Supported

project/Dependencies.scala
Refs https://github.com/akka/alpakka/issues/2400
=> Alpakka 2.0.2 (Netty override)

build.sbt, docs/src/main/paradox/eventsourced.md, docs/src/main/paradox/getting-started/event-generator-app.md, docs/src/main/paradox/getting-started/running-cluster.md, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/running.md, examples/src/test/java/jdocs/guide/EventGeneratorApp.java, examples/src/test/scala/docs/eventsourced/ShoppingCart.scala, examples/src/test/scala/docs/guide/EventGeneratorApp.scala
=> clarify tagging and hide EventGeneratorApp, #449

docs/src/main/paradox/overview.md, docs/src/main/paradox/slick.md
=> clarify that Slick module is community-driven

.github/release-drafter.yml, .github/workflows/release-drafter.yml
(just doing some gardening)
Copy pasted from https://github.com/playframework/play-json/blob/master/.github/workflows/release-drafter.yml cc @ennru
=> Adds release drafter

build.sbt, project/CopyrightHeader.scala
=> Enable header check for it tests

akka-projection-kafka/src/it/scala/akka/projection/kafka/KafkaSpecBase.scala, project/Dependencies.scala
Final release with testcontainer updates for Alpakka Kafka testkit.
=> Alpakka Kafka 2.0.6

docs/src/main/paradox/jdbc.md, docs/src/main/paradox/slick.md
Minor improvement for the scheman change note. 
It mentions H2 database and make the visuazliation of the settings more explicit.
=> Improvement on note about schema change

docs/src/main/paradox/actor.md
* It's already mentioned in api docs
=> Clarify actor lifecycle

examples/src/it/java/jdocs/cassandra/CassandraProjectionDocExample.java
=> Fix Java pause/resume docs example to finish with resume #557

akka-projection-durable-state/src/main/scala/akka/projection/state/javadsl/DurableStateSourceProvider.scala, akka-projection-durable-state/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider.scala, akka-projection-durable-state/src/test/scala/akka/projection/state/scaladsl/DurableStateSourceProviderSpec.scala, build.sbt, docs/src/main/paradox/durable-state.md, docs/src/main/paradox/index.md, docs/src/main/paradox/overview.md, examples/src/test/java/jdocs/state/AccountEntity.java, examples/src/test/java/jdocs/state/CborSerializable.scala, examples/src/test/java/jdocs/state/DurableStateStoreDocExample.java, examples/src/test/scala/docs/state/AccountEntity.scala, examples/src/test/scala/docs/state/CborSerializable.scala, examples/src/test/scala/docs/state/DurableStateStoreDocExample.scala, project/Dependencies.scala, project/project-info.conf
=> Durable state projection

.scala-steward.conf
=> fix: exclude jackson from scala steward

akka-projection-core/src/main/scala/akka/projection/BySlicesSourceProvider.scala, akka-projection-durable-state/src/main/scala/akka/projection/state/javadsl/DurableStateSourceProvider.scala, akka-projection-durable-state/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala, docs/src/main/paradox/durable-state.md, docs/src/main/paradox/eventsourced.md, docs/src/main/paradox/index.md, examples/src/test/java/jdocs/eventsourced/EventSourcedBySlicesDocExample.java, examples/src/test/java/jdocs/eventsourced/EventSourcedDocExample.java, examples/src/test/java/jdocs/state/DurableStateStoreBySlicesDocExample.java, examples/src/test/java/jdocs/state/DurableStateStoreDocExample.java, examples/src/test/scala/docs/eventsourced/EventSourcedDocExample.scala, examples/src/test/scala/docs/state/DurableStateStoreDocExample.scala, project/AkkaSnapshotRepository.scala, project/Dependencies.scala
* using a snapshot version of Akka
* and documentation of SourceProvider for eventsBySlices and changesBySlices
=> Add slices to EventSourcedProvider and DurableStateSourceProvider

akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala, akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/scaladsl/ProjectionTestKit.scala
=> improved retryAndFail tests

akka-projection-core-test/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala
=> Fix test of stopping ProjectionBehavior

akka-projection-cassandra/src/it/scala/akka/projection/cassandra/CassandraProjectionSpec.scala
=> ensure check of offset repo is wrapped with 'eventually'

LICENSE, project/Common.scala
https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
=> Change license

.github/workflows/checks.yml, .github/workflows/integration-tests-cassandra.yml, .github/workflows/integration-tests-jdbc.yml, .github/workflows/integration-tests-kafka.yml, .github/workflows/integration-tests-slick.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml, docs/src/main/paradox/getting-started/running.md, docs/src/main/paradox/overview.md, docs/src/main/paradox/snapshots.md, project/Common.scala
To change your local clone:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> Rename master branch to main

akka-projection-durable-state/src/main/scala/akka/projection/state/javadsl/DurableStateSourceProvider.scala, akka-projection-durable-state/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala
* power user API when the query plugin instance has custom configuration (or programatic setup)
=> Query plugin paramater in source providers

project/Dependencies.scala
=> Update Slick to 3.4.1

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/GrpcReadJournalProvider.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/ProtoAnySerialization.scala, docs/src/main/paradox/grpc.md, samples/grpc/shopping-analytics-service-java/src/main/java/shopping/analytics/ShoppingCartEventConsumer.java, samples/grpc/shopping-analytics-service-scala/src/main/scala/shopping/analytics/ShoppingCartEventConsumer.scala
=> Follow up on some small FIXME

docs/src/main/paradox/grpc.md
Not as nice as the downloadable zip files we have in the guide, but good enough for now.
=> Link to gRPC samples

akka-projection-slick/src/it/scala/akka/projection/slick/SlickContainerOffsetStoreSpec.scala, project/AkkaSnapshotRepository.scala, project/Common.scala, project/Dependencies.scala, project/Protobuf.scala, project/SequentialTestExecution.scala, project/build.properties, project/plugins.sbt, samples/grpc/shopping-analytics-service-scala/project/build.properties, samples/grpc/shopping-cart-service-scala/project/build.properties
=> bump: sbt 1.7.2 and plugins; Scala versions

akka-projection-durable-state/src/main/scala/akka/projection/state/javadsl/DurableStateSourceProvider.scala, akka-projection-durable-state/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider.scala
not sure if tests are necessary for change
=> fix: handle DeletedDurableState in extractCreationTime implementations

docs/release-train-issue-template.md, project/Common.scala
Ported from 1.3.x + update to release train
=> build: Automatically set license url based on version

samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt
=> Bump samples to 1.3.1

.github/workflows/checks.yml, .github/workflows/fossa.yml, .github/workflows/integration-tests-cassandra.yml, .github/workflows/integration-tests-grpc.yml, .github/workflows/integration-tests-jdbc.yml, .github/workflows/integration-tests-kafka.yml, .github/workflows/integration-tests-slick.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml
- explicit permissions
- select action version by exact git hash
=> ci: GH workflow security hardening

samples/grpc/shopping-cart-service-java/src/main/resources/persistence.conf, samples/grpc/shopping-cart-service-scala/src/main/resources/persistence.conf
Already present int the right place
=> fix: Publish-events in wrong place in sample config

samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/src/main/resources/application.conf, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
References https://github.com/akka/akka-diagnostics/issues/19
=> feat: enable config checker

.github/workflows/dependency-submission.yml
=> chore: full hash to reference submission action

project/Common.scala
CI shouldn't spend cycles on code formatting.
=> chore: don't format code on CI

akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/replication/ReplicationIntegrationSpec.scala, akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/replication/ReplicationJavaDSLIntegrationSpec.scala, build.sbt, samples/replicated/shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCart.java, samples/replicated/shopping-cart-service-scala/src/main/scala/shopping/cart/ShoppingCart.scala
Waiting for next milestone of r2dbc before we can merge
=> chore: Use R2DBC convenience factories for replication

samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
References https://github.com/akka/akka-projection/issues/800
=> bump: Update gRPC RES samples to projection 1.4.0-M3

.github/workflows/dependency-submission.yml
=> chore: exclude parts from dependency graph submission

akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/IntegrationSpec.scala, akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala, akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto, akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/ConsumerFilter.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
on top of https://github.com/akka/akka-projection/pull/816
=> feat: Replay events via explicit replay request

akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/FilterStageSpec.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/FilterStage.scala
Follow up to https://github.com/akka/akka-projection/pull/818#discussion_r1144751730
=> test: Additional test of replay parallelism

akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala, akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala, akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
Follow up on @octonato 's suggestion https://github.com/akka/akka-projection/pull/837#discussion_r1155979711
=> chore: rename R2dbcOffsetStore.isAccepted to validate

.github/workflows/release.yml, build.sbt, project/Dependencies.scala, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/build.sbt
This should be the last change before merging dev-filter back to main
=> bump: akka-persistence-r2dbc 1.1.0-M8

project/Dependencies.scala
References https://github.com/akka/alpakka-kafka/releases/tag/v4.0.2
=> bump: Alpakka Kafka 4.0.2

project/Dependencies.scala
=> chore: Remove scala-collection-compat dependency, #829

akka-projection-core-test/src/test/scala/akka/projection/internal/HandlerRecoveryImplSpec.scala, akka-projection-core-test/src/test/scala/akka/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala, akka-projection-jdbc/src/main/scala/akka/projection/jdbc/internal/JdbcProjectionImpl.scala, akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala, akka-projection-testkit/src/main/scala/akka/projection/testkit/internal/TestProjectionImpl.scala
Popped up [here](https://github.com/akka/akka-management/pull/1134#discussion_r1172488640).
=> fix: logger with proper class ref

samples/grpc/shopping-analytics-service-java/kubernetes/akka-cluster.yml, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/kubernetes/akka-cluster.yml, samples/grpc/shopping-cart-service-java/kubernetes/akka-cluster.yml, samples/grpc/shopping-cart-service-java/kubernetes/service.yml, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-java/src/main/resources/persistence.conf, samples/grpc/shopping-cart-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/kubernetes/akka-cluster.yml, samples/grpc/shopping-cart-service-scala/kubernetes/service.yml, samples/grpc/shopping-cart-service-scala/src/main/resources/persistence.conf, samples/replicated/shopping-cart-service-java/kubernetes/akka-cluster.yml, samples/replicated/shopping-cart-service-java/kubernetes/service.yml, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/kubernetes/akka-cluster.yml, samples/replicated/shopping-cart-service-scala/kubernetes/service.yml
A few fixes to the samples, there will probably be more because I haven't tested replicated samples yet.
* Missing DB_PASSWORD config
* grpc environment variables and kubernetes service
* Java 17 base image
I will update the Kubernetes step in the guide in a separate PR and there also add some notes about load balancers and cross region setup.
=> doc: Fix samples after testing in aws

docs/src/main/paradox/r2dbc.md, docs/src/main/paradox/running.md
=> doc: Scaling projection instances

LICENSE
1.4.1 had some partial failure when uploading to sonatype, and it doesn't accept retry of same artificts
=> chore: License change date for 1.4.2

akka-projection-r2dbc/src/it/resources/application-h2.conf, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/DurableStateEndToEndSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedChaosSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedPubSubSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala, akka-projection-r2dbc/src/main/resources/h2-default-projection-schema.conf, docs/src/main/paradox/r2dbc.md
References #935
Added dialect in test names as well for easier tracking in case test failures are related to some specific dialect
=> feat: Default H2 schema through config instead of copy-paste 

akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala, akka-projection-grpc-tests/src/it/scala/akka/projection/grpc/replication/ReplicationJavaDSLIntegrationSpec.scala, akka-projection-grpc-tests/src/test/java/akka/projection/grpc/producer/javadsl/ProducerCompileTest.java, akka-projection-grpc-tests/src/test/java/akka/projection/grpc/replication/javdsl/ReplicationCompileTest.java, akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/internal/EventProducerServiceSpec.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventProducerServiceImpl.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/EventProducerSettings.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducer.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/javadsl/EventProducerSource.scala, akka-projection-grpc/src/main/scala/akka/projection/grpc/producer/scaladsl/EventProducer.scala, docs/src/main/paradox/eventsourced.md, docs/src/main/paradox/grpc.md, project/Dependencies.scala, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-java/src/main/java/shopping/cart/PublishEvents.java, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
See https://github.com/akka/akka/pull/31980
See https://github.com/akka/akka-persistence-r2dbc/pull/410
=> feat: Snapshots as starting point

akka-distributed-cluster-docs/src/main/paradox/guide/2-service-to-service.md, docs/src/main/paradox/durable-state.md, docs/src/main/paradox/eventsourced.md, docs/src/main/paradox/grpc.md
* and fixing a few links
Draft because new Akka version must be released first
=> chore: EventsBySliceFirehoseQuery in docs

akka-projection-durable-state/src/main/mima-filters/1.4.2.backwards.excludes/start-offset.excludes, akka-projection-durable-state/src/main/scala/akka/projection/state/javadsl/DurableStateSourceProvider.scala, akka-projection-eventsourced/src/main/mima-filters/1.4.2.backwards.excludes/start-offset.excludes, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/javadsl/EventSourcedProvider.scala, akka-projection-eventsourced/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider.scala, akka-projection-grpc-tests/src/test/java/akka/projection/grpc/consumer/javadsl/ConsumerCompileTest.java, akka-projection-grpc-tests/src/test/scala/akka/projection/grpc/consumer/ConsumerDocSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala, docs/src/main/paradox/grpc.md
* mostly intended for Projections over gRPC
=> feat: Start projection from custom offset

samples/grpc/shopping-analytics-service-scala/src/main/resources/application.conf
=> chore: log-level config typo

akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
So that it can be composed with other services using `ServiceHandler.concatOrNotFound`
=> feat: Producer push grpc service partial for composing

akka-projection-grpc/src/main/mima-filters/1.5.0-M3.backwards.excludes/event-producer-push-protobuf.excludes, akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/EventProducerPushDestination.scala
=> fix: Right return type for producer push partial grpc handlers

akka-projection-grpc-tests/src/it/resources/persistence.conf, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/EventSourcedPubSubSpec.scala, samples/grpc/restaurant-drone-deliveries-service-java/src/main/resources/persistence.conf, samples/grpc/restaurant-drone-deliveries-service-scala/src/main/resources/persistence.conf
* let's use defaults until we have good reasons to adjust
* some of these might be candidates for tuning when running perf tests
=> chore: cleanup of some r2dbc config

.github/workflows/checks.yml, samples/grpc/iot-service-scala/README.md, samples/grpc/iot-service-scala/src/main/scala/iot/registration/RegistrationEvents.scala, samples/grpc/iot-service-scala/src/test/scala/iot/EdgeApp.scala
* and adding iot-service to ci checks
=> chore: One more CborSerializable

akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala, akka-projection-r2dbc/src/main/mima-filters/1.5.0-M4.backwards.excludes/r2dbc-session.excludes, akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/javadsl/R2dbcSession.scala, akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcSession.scala
* corresponding to akka.persistence.r2dbc.session..R2dbcSession
* also noticed that javadsl had wrong function type, ApiMayChange so just changed, and removed ApiMayChange
=> feat: Add R2dbcSession.withSession

docs/src/main/paradox/grpc.md
Should read "include", and not "exclude".
=> Corrected gRPC docs

.github/workflows/checks.yml, .github/workflows/dependency-submission.yml, project/AkkaDisciplinePlugin.scala, project/Dependencies.scala
See https://github.com/akka/akka/pull/32125
=> chore: Drop Scala 2.12

.github/workflows/release.yml
Oversight in https://github.com/akka/akka-projection/pull/1033
=> build: publishSigned

samples/grpc/local-drone-control-scala/src/main/resources/application.conf
=> sample: Fix config typo of active-entity-limit

project/plugins.sbt
References
- https://github.com/akka/akka-paradox/releases/tag/v0.53
=> bump: Akka Paradox

project/Dependencies.scala, project/plugins.sbt, samples/grpc/iot-service-scala/build.sbt, samples/grpc/iot-service-scala/project/plugins.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/local-drone-control-scala/project/plugins.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/project/plugins.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/project/plugins.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/project/plugins.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/project/plugins.sbt
* and swithching other milestone versions to final
=> bump: Akka 2.9.0

scripts/prepare-downloads.sh
=> doc: Fix mistake in tag replace in zips

akka-projection-grpc/src/main/mima-filters/1.5.0.backwards.excludes/fill_sequence_number_gaps.excludes, akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_consumer.proto, akka-projection-grpc/src/main/scala/akka/projection/grpc/internal/EventPusherConsumerServiceImpl.scala, project/Dependencies.scala, samples/grpc/iot-service-scala/src/main/resources/persistence.conf
See https://github.com/akka/akka/pull/32237
Requires an Akka release
=> feat: Fill sequence number gaps via message from producer

akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_consumer.proto, akka-projection-grpc/src/main/protobuf/akka/projection/grpc/event_producer.proto
* mistake from previous additions, but never released
=> chore: Proto field numbers

akka-projection-jdbc/src/it/scala/akka/projection/jdbc/JdbcProjectionSpec.scala, akka-projection-r2dbc/src/it/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala, akka-projection-slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala
* make it more similar to R2dbcProjectionSpec
Refs https://github.com/akka/akka-projection/issues/768
=> test: Harden SlickProjectionSpec

.github/workflows/checks.yml, .github/workflows/dependency-submission.yml, .github/workflows/fossa.yml, .github/workflows/integration-tests-cassandra.yml, .github/workflows/integration-tests-grpc.yml, .github/workflows/integration-tests-jdbc.yml, .github/workflows/integration-tests-kafka.yml, .github/workflows/integration-tests-r2dbc.yml, .github/workflows/integration-tests-slick.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml
Main target was the sbt-dependency-submission, but I went over all.
=> bump: current versions of all GitHub actions

.github/workflows/checks.yml
No need to tell us progress on downloading artifacts.
=> build: no transfer progress for maven ci builds

samples/grpc/iot-service-rs/Cargo.toml, samples/grpc/iot-service-rs/backend/src/temperature.rs
Declares the number of bits used for the event type.
Requires: https://github.com/akka/akka-edge-rs/pull/144
=> Declare the event type bit size

LICENSE
=> chore: License change date for 1.5.3

samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/project/plugins.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/project/plugins.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/project/plugins.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/project/plugins.sbt
* java samples fail with: malformed header: missing HTTP content-type
=> bump: akka-grpc 2.4.1

.fossa.yml, .github/workflows/checks.yml, .github/workflows/fossa.yml, .github/workflows/integration-tests-cassandra.yml, .github/workflows/integration-tests-grpc.yml, .github/workflows/integration-tests-jdbc.yml, .github/workflows/integration-tests-kafka.yml, .github/workflows/integration-tests-r2dbc.yml, .github/workflows/integration-tests-slick.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml, README.md, docs/release-train-issue-template.md, project/plugins.sbt, project/project-info.conf
References https://github.com/lightbend/akka-meta/issues/428
=> chore: repo gardening

akka-projection-grpc-integration/src/test/resources/db/default-init.sql, akka-projection-grpc/ddl-scripts/create_tables_postgres.sql, akka-projection-r2dbc/ddl-scripts/create_tables_postgres.sql, akka-projection-r2dbc/ddl-scripts/create_tables_yugabyte.sql, samples/grpc/iot-service-java/ddl-scripts/create_tables.sql, samples/grpc/iot-service-scala/ddl-scripts/create_tables.sql, samples/grpc/local-drone-control-java/autoscaling/local/persistence/templates/postgresql-initdb-configmap.yaml, samples/grpc/local-drone-control-java/ddl-scripts/create_tables.sql, samples/grpc/local-drone-control-scala/autoscaling/local/persistence/templates/postgresql-initdb-configmap.yaml, samples/grpc/local-drone-control-scala/ddl-scripts/create_tables.sql, samples/grpc/restaurant-drone-deliveries-service-java/ddl-scripts/create_tables.sql, samples/grpc/restaurant-drone-deliveries-service-scala/ddl-scripts/create_tables.sql, samples/grpc/shopping-analytics-service-java/ddl-scripts/create_tables.sql, samples/grpc/shopping-analytics-service-scala/ddl-scripts/create_tables.sql, samples/grpc/shopping-cart-service-java/ddl-scripts/create_tables.sql, samples/grpc/shopping-cart-service-scala/ddl-scripts/create_tables.sql, samples/replicated/shopping-cart-service-java/ddl-scripts/create_tables.sql, samples/replicated/shopping-cart-service-scala/ddl-scripts/create_tables.sql
Mentioned in https://github.com/akka/akka-persistence-r2dbc/issues/558#issuecomment-2071979388
=> chore: drop revision from Durable State primary key and related index

project/plugins.sbt, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/project/plugins.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/project/plugins.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/project/plugins.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/project/plugins.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/project/plugins.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/project/plugins.sbt
References https://github.com/akka/akka-grpc/issues/1939
=> bump: Akka gRPC 2.4.2

project/Dependencies.scala, project/plugins.sbt, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/iot-service-scala/project/plugins.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/local-drone-control-scala/project/plugins.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/project/plugins.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/project/plugins.sbt
* Akka 2.9.3
* Akka HTTP 10.6.3
* Akka gRPC 2.4.3
* Akka Persistence JDBC 5.4.1
* Akka Persistence R2DB 1.2.4
* Alpakka 8.0.0
* Alpakka Kafka 6.0.0
* Akka Paradox Theme 0.57
Some transitives:
* Slick 3.5.1
* H2 (for tests) 2.2.224
=> bump: Akka umbrella

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-java/src/main/java/iot/temperature/TemperatureEvents.java, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
References https://github.com/akka/akka-projection/issues/1157
=> chore: License change date and sample bump for 1.5.4

docs/release-train-issue-template.md
Updating the grpc samples already a part of the steps
=> build: Small fix in release template

project/Dependencies.scala, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-scala/autoscaling/simulator/build.sbt, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/build.sbt
=> bump: Bump Scala to fix samples on sbt 1.10.0

project/Dependencies.scala, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/build.sbt
=> bump: akka 2.9.5

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update license change date for 1.5.5

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
* and update version in samples
=> chore: Update license change date for 1.5.6

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update license change date for 1.5.7

build.sbt
Missed the taget dir.
References
- #1202
=> docs: revise URL structure (libraries) 2

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: License change date and 1.5.8 release preparations

LICENSE, akka-projection-grpc/src/main/scala/akka/projection/grpc/consumer/scaladsl/GrpcReadJournal.scala, build.sbt, docs/src/main/paradox/slick.md, project/Common.scala, project/Dependencies.scala, project/plugins.sbt, project/project-info.conf, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/iot-service-scala/project/plugins.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/local-drone-control-scala/project/plugins.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/project/plugins.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/project/plugins.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/project/plugins.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/project/plugins.sbt, worksheet.sc
Successor of https://github.com/akka/akka-projection/pull/1235
=> chore: Pre 24.10 release

docs/src/main/paradox/durable-state.md
References https://github.com/akka/akka-projection/issues/1219
=> docs: highlighting durable state semantics

LICENSE, project/Dependencies.scala, project/project-info.conf, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: changes for release 1.6.1

docs/release-train-issue-template.md, project/Dependencies.scala, project/project-info.conf
=> bump: akka-persistence-dynamodb 2.0.1

README.md, build.sbt, docs/src/main/paradox/cassandra.md, docs/src/main/paradox/durable-state.md, docs/src/main/paradox/kafka.md, docs/src/main/paradox/overview.md
Avoid broken links and redirects.
=> docs: link fixes

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update change date for 1.6.3

.github/workflows/link-validator.yml, project/Common.scala, project/plugins.sbt, scripts/link-validator-distributed-cluster.conf, scripts/link-validator-edge.conf
Use the latest Akka theme.
Even check the Edge and Distributed cluster sites.
=> docs: even more links

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update change date for 1.6.4

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
Refs #1280
Leaving same change date as previous release (still the same day in US).
=> chore: update license and samples to 1.6.5

project/Dependencies.scala
https://github.com/akka/akka-persistence-r2dbc/releases/tag/v1.3.1
=> bump: akka-persistence-r2dbc 1.3.1

LICENSE, project/Dependencies.scala, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update license change date for 1.6.6

samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
I should have done this in https://github.com/akka/akka-projection/pull/1298
but they should work with 1.3.0 as well.
=> chore: Update r2dbc 1.3.1 in samples

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: updates for release 1.6.7

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update license change date for 1.6.8

akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/PostgresOffsetStoreDao.scala, akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/internal/SqlServerOffsetStoreDao.scala
Missed this in failing tests previously
=> fix: SQL Server limit syntax

project/Dependencies.scala
We'll probably make a release with https://github.com/akka/akka-projection/pull/1313 soon.
I'd like to bump r2dbc to promote bugfix https://github.com/akka/akka-persistence-r2dbc/pull/656
=> bump: akka-persistence-r2dbc 1.3.3

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: updates for release 1.6.9

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update change date for 16.10

akka-projection-dynamodb/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala
* log envelope about to be processed (in flight)
* log offsets stored
* enable logging with:
```
<logger name="akka.projection.dynamodb.internal.DynamoDBOffsetStore" level="TRACE" />
```
=> chore: Additional trace logging in DynamoDBOffsetStore

akka-projection-grpc/src/main/mima-filters/1.6.11-M2.backwards.excludes/grpc-bump.excludes, project/Dependencies.scala, project/plugins.sbt, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/iot-service-scala/project/plugins.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/local-drone-control-scala/project/plugins.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-scala/project/plugins.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-analytics-service-scala/project/plugins.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/grpc/shopping-cart-service-scala/project/plugins.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-scala/project/plugins.sbt
=> bump: Akka core 2.10.3, grpc 2.5.3, r2dbc 1.3.3

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update change date for 16.11

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update change date for 1.6.12

project/Dependencies.scala, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
References
- https://github.com/akka/akka-persistence-r2dbc/issues/672
=> bump: Akka Persistence R2DBC 1.3.5

project/Dependencies.scala, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
- https://github.com/akka/akka-persistence-r2dbc/issues/676
- https://github.com/akka/akka-persistence-r2dbc/releases/tag/v1.3.6
=> bump: akka-persistence-r2dbc 1.3.6

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
References https://github.com/akka/akka-projection/issues/1342
=> chore: License change and sample bump for 1.6.13

project/Dependencies.scala
References
- https://github.com/akka/alpakka-kafka/releases/tag/v7.0.4
- [CVE-2025-27817](https://github.com/advisories/GHSA-vgq5-3255-v292)
=> bump: Alpakka Kafka 7.0.4 (was 7.0.2)

LICENSE, samples/grpc/iot-service-java/pom.xml, samples/grpc/iot-service-scala/build.sbt, samples/grpc/local-drone-control-java/pom.xml, samples/grpc/local-drone-control-scala/build.sbt, samples/grpc/restaurant-drone-deliveries-service-java/pom.xml, samples/grpc/restaurant-drone-deliveries-service-scala/build.sbt, samples/grpc/shopping-analytics-service-java/pom.xml, samples/grpc/shopping-analytics-service-scala/build.sbt, samples/grpc/shopping-cart-service-java/pom.xml, samples/grpc/shopping-cart-service-scala/build.sbt, samples/replicated/shopping-cart-service-java/pom.xml, samples/replicated/shopping-cart-service-scala/build.sbt
=> chore: Update license change date for 1.6.15
